calendario/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

urlpatterns = [
    path('calendario/', views.calendario),
    path('edita_evento/', views.edita_evento),
    path('crea_evento/', views.crea_evento),
    path('calendario_ajax/', views.calendario_ajax),
]
# url(r'^mod_recordatorio/$', views.mod_recordatorio,  name='mod_recordatorio'),
# url(r'^muestra_calendario/$', views.muestra_calendario,  name='muestra_calendario'),
# url(r'^mis_eventos/$', views.mis_eventos,  name='mis_eventos'),
# url(r'^ver_acontecimiento/$', views.ver_acontecimiento,  name='ver_acontecimiento'),
# url(r'^acontecimiento_importante/$', views.acontecimiento_importante,  name='acontecimiento_importante'),

vut/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

urlpatterns = [
    path('viviendas/', views.viviendas),
    path('ajax_viviendas/', views.ajax_viviendas),
    path('reservas_vut/', views.reservas_vut),
    path('ajax_reservas_vut/', views.ajax_reservas_vut),
    path('viajeros/', views.viajeros),
    path('contabilidad_vut/', views.contabilidad_vut),
    path('ajax_contabilidad_vut/', views.ajax_contabilidad_vut),
    path('domotica_vut/', views.domotica_vut),
    path('ajax_domotica_vut/', views.ajax_domotica_vut),
    path('viviendas_registradas_vut/', views.viviendas_registradas_vut),
    path('registro_viajero_manual/', views.registro_viajero_manual),
    path('web_vut/', views.web_vut),
    path('web_vut_id/<int:vivienda_id>/', views.web_vut_id),
    path('reserva_vut_crea_recibo/<int:reserva_id>/', views.reserva_vut_crea_recibo),
    path('rvpd/<str:secret_id>/', views.rvpd),
    path('contratos_vut/', views.contratos_vut),
    path('firconvut/<str:secret_id>/<str:n>/', views.firconvut),
    # path('web_vut_id/', views.web_vut_id),
    path('getvuts/<int:entidad_code>/', views.getvuts),
    path('verlibroregistros/<int:id_vivienda>/', views.verlibroregistros),
]

calendario/models.py
# -*- coding: utf-8 -*-
from django.db import models
from actas.models import Convocatoria

# from autenticar.models import Gauser, Gauser_extra
# from entidades.models import Subentidad, Entidad, Ronda

from autenticar.models import Gauser
from entidades.models import Subentidad, Entidad, Ronda, Gauser_extra, Cargo

# from entidades.models import Gauser_extra as GE

# class Valarm(models.Model):
#     action = models.CharField('ACTION', max_length=10, default='EMAIL', editable=False)
#     summary = models.CharField('SUMMARY', max_length=150, blank=True, null=True)
#     description = models.TextField('DESCRIPTION', blank=True, null=True)
#     trigger1 = models.DateTimeField('TRIGGER', blank=True, null=True)
#     trigger2 = models.DurationField('Cuanto tiempo antes del evento se debe avisar', blank=True, null=True)


# http://www.kanzaki.com/docs/ical/

propietarios_id = [19, 640, 67, 2699, 75, 76, 77, 15, 81, 12128, 107, 52, 53, 11770, 58, 14607, 93]

propietarios = [(15, u' Javier', u'Anero Tejada'), (19, u' M Lourdes', u'Atares Bescos'),
 (52, u' M Aurora', u'Garc\xeda Fern\xe1ndez de Larrea'), (53, u' Federico Jos\xe9', u'Garc\xeda Garc\xeda'),
 (58, u' Milagros', u'G\xf3mez Crist\xf3bal'), (67, u' Alex\xe1nder', u'Iturbe Laskurain'),
 (75, u' Fabi\xe1n', u'Mart\xedn Herce'), (76, u'Miguel \xc1ngel', u'Mart\xedn N\xfa\xf1ez'),
 (77, u' Juan Jos\xe9', u'Mart\xedn Romero'), (81, u' Sergio', u'Mata Tob\xeda'),
 (93, u' Ignacio', u'P\xe9rez L\xf3pez de Luzuriaga'), (107, u' Sara', u'Sacrist\xe1n Tob\xedas'),
 (640, u'Mar\xeda Blanca', u'Lara Serna'), (2699, u' Natividad', u'Narvarte Sanz'),
 (11770, u' Marta Isabel', u'Arribas Camargo'), (12128, u' Diego', u'Guerrero Vivar'),
 (14607, u'Mar\xeda Montserrat', u'Benito S\xe1nchez')]

propietarios_asocia = [(3355, u' Javier', u'Anero Tejada'), (3357, u' M Lourdes', u'Atares Bescos'),
 (3386, u' M Aurora', u'Garc\xeda Fern\xe1ndez de Larrea'), (3387, u' Federico Jos\xe9', u'Garc\xeda Garc\xeda'),
 (3392, u' Milagros', u'G\xf3mez Crist\xf3bal'), (3402, u' Alex\xe1nder', u'Iturbe Laskurain'),
 (3412, u' Fabi\xe1n', u'Mart\xedn Herce'), (3413, u'Miguel \xc1ngel', u'Mart\xedn N\xfa\xf1ez'),
 (72, u' Juan Jos\xe9', u'Mart\xedn Romero'), (3419, u' Sergio', u'Mata Tob\xeda'),
 (3432, u' Ignacio', u'P\xe9rez L\xf3pez de Luzuriaga'), (3445, u' Sara', u'Sacrist\xe1n Tob\xedas'),
 (5983, u'Mar\xeda Blanca', u'Lara Serna'), (3422, u' Natividad', u'Narvarte Sanz'),
 (3356, u' Marta Isabel', u'Arribas Camargo'), (3395, u' Diego', u'Guerrero Vivar'),
 (5979, u'Mar\xeda Montserrat', u'Benito S\xe1nchez')]

STATUS = (('CONFIRMED', 'Confirmado'), ('TENTATIVE', 'Tentativa'), ('CANCELLED', 'Cancelado'))
TRANS = (('TRANSPARENT', 'Evento transparente en el tiempo'), ('OPAQUE', 'Opaco en el tiempo'))
FREQ = (('MINUTELY', 'Cada minuto'), ('HOURLY', 'Cada hora'), ('DAILY', 'Diariamente'), ('WEEKLY', 'Semanalmente'),
        ('MONTHLY', 'Mensualmente'), ('YEARLY', 'Anualmente'))


class Vevent(models.Model):
    entidad = models.ForeignKey(Entidad, blank=True, null=True, on_delete=models.CASCADE)
    invitados = models.ManyToManyField(Gauser, blank=True, related_name='invitados')
    subentidades = models.ManyToManyField(Subentidad, blank=True)
    cargos = models.ManyToManyField(Cargo, blank=True)
    propietarios = models.ManyToManyField(Gauser, blank=True, related_name='propietarios')
    dtstart = models.DateTimeField('DTSTART')
    dtend = models.DateTimeField('DTEND', blank=True, null=True)
    # dtstamp = models.DateTimeField('DTSTAMP', blank=True, null=True)
    uid = models.CharField('UID', max_length=100, blank=True, null=True)
    created = models.DateField('CREATED', auto_now_add=True)
    summary = models.CharField('SUMMARY', max_length=150)
    description = models.TextField('DESCRIPTION', blank=True, null=True)
    modified = models.DateField('LAST-MODIFIED', auto_now=True)
    location = models.CharField('LOCATION', max_length=100, blank=True, null=True)
    sequence = models.IntegerField('SEQUENCE', blank=True, null=True)
    trans = models.CharField('TRANSPARENCY', max_length=15, choices=TRANS, default='TRANSPARENT')
    # RRULE infomation:
    freq = models.CharField('FREQ (rrule)', max_length=10, choices=FREQ, blank=True, null=True)
    count = models.IntegerField('COUNT (rrule)', blank=True, null=True)
    interval = models.IntegerField('INTERVAL (rrule)', blank=True, null=True)
    until = models.DateTimeField('UNTIL (rrule)', blank=True, null=True)
    # La especificación permite definir varias alarmas. Deberíamos entonces crear una clase Valarm y aquí
    # un ManyToMany
    action_alarm = models.CharField('ACTION (alarm)', max_length=10, default='EMAIL', editable=False)
    summary_alarm = models.CharField('SUMMARY (alarm)', max_length=150, blank=True, null=True)
    description_alarm = models.TextField('DESCRIPTION (alarm)', blank=True, null=True)
    trigger1_alarm = models.DateTimeField('TRIGGER (alarm)', blank=True, null=True)
    trigger2_alarm = models.DurationField('Cuanto tiempo antes del evento se debe avisar', blank=True, null=True)
    festivo = models.BooleanField('¿Es festivo?', default=False)

    def __str__(self):
        return u'%s (%s)' % (self.summary, self.dtstart)


class Calendar(models.Model):
    gauser = models.ForeignKey(Gauser, on_delete=models.CASCADE)
    entidad = models.ForeignKey(Entidad, on_delete=models.CASCADE)
    calname = models.CharField('Nombre del calendario', max_length=150)
    vevents = models.ManyToManyField(Vevent, blank=True)

    def __str__(self):
        return u'Calendario de: %s (%s)' % (self.gauser.get_full_name(), self.calname)

calendario/views.py
# -*- coding: utf-8 -*-
from datetime import datetime, timedelta
import logging
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.db.models import Q
from django import forms
from django.http import HttpResponse, JsonResponse
from django.template.loader import render_to_string

# from autenticar.models import Gauser_extra, Gauser
# from entidades.models import Subentidad
from autenticar.models import Gauser
from entidades.models import Subentidad, Gauser_extra, Cargo

from gauss.rutas import *
from calendario.models import Vevent, Calendar
from gauss.funciones import usuarios_de_gauss
from mensajes.views import crear_aviso, crea_mensaje_cola
from mensajes.models import Aviso, Mensaje, Etiqueta
from gtelegram.views import envia_telegram
import calendar
from dateutil.relativedelta import relativedelta
from django.db.models.fields.related import ManyToManyField
import simplejson as json

logger = logging.getLogger('django')


def to_dict(instance):
    opts = instance._meta
    data = {}
    for f in opts.concrete_fields + opts.many_to_many:
        if isinstance(f, ManyToManyField):
            if instance.pk is None:
                data[f.name] = []
            else:
                data[f.name] = list(f.value_from_object(instance).values_list('pk', flat=True))
        else:
            data[f.name] = f.value_from_object(instance)
    return data


def vevents_month(g_e, fecha):
    return Vevent.objects.filter(
        Q(cargos__in=g_e.cargos.all()) | Q(subentidades__in=g_e.subentidades_hijos()) | Q(
            invitados__in=[g_e.gauser]) | Q(propietarios__in=[g_e.gauser]),
        Q(dtstart__month=fecha.month) | Q(dtend__month=fecha.month)).distinct()


def vevents_agenda(g_e, fecha, meses):
    fecha = datetime.combine(fecha, datetime.min.time())
    return Vevent.objects.filter(Q(cargos__in=g_e.cargos.all()) | Q(subentidades__in=g_e.subentidades_hijos()) | Q(
        invitados__in=[g_e.gauser]) | Q(
        propietarios__in=[g_e.gauser]), dtend__gte=fecha, dtstart__lte=meses[-1][-1]).distinct()


@login_required()
def calendario(request):
    g_e = request.session["gauser_extra"]
    # vista = {'mes': 'calendario_month.html', 'agenda': 'calendario_agenda.html', 'semana': 'calendario_semana.html'}
    # Las siguientes líneas son para eliminar el superusuario entidad.code si ya se han creado otros usuarios:
    if Gauser_extra.objects.filter(ronda=g_e.ronda).count() > 3:
        try:
            g_eborrar = Gauser_extra.objects.get(ronda=g_e.ronda, gauser__username=g_e.ronda.entidad.code)
            gborrar = g_eborrar.gauser
            g_eborrar.delete()
            gborrar.delete()
        except:
            pass
    if request.method == 'POST':
        vista_actual = request.POST['vista_actual']
        fecha = datetime.strptime(request.POST['fecha_actual'], '%d/%m/%Y')

        if request.POST['action'] == 'borrar_evento':
            vevent = Vevent.objects.get(id=request.POST['id_evento'])
            if g_e.gauser in vevent.propietarios.all():
                vevent.delete()
            elif g_e.has_cargos([1]):  # Si es un cargo de nivel 1
                vevent.delete()
            elif g_e.gauser in vevent.invitados.all():
                vevent.invitados.remove(g_e.gauser)

        if vista_actual == 'month':
            mes = calendar.Calendar().monthdatescalendar(fecha.year, fecha.month)
            # vevents = Vevent.objects.filter(
            #     Q(subentidades__in=g_e.subentidades_hijos()) | Q(invitados__in=[g_e.gauser]) | Q(
            #         propietarios__in=[g_e.gauser]),
            #     Q(dtstart__month=fecha.month) | Q(dtend__month=fecha.month)).distinct()
            vevents = vevents_month(g_e, fecha)
            renderizado = render_to_string('calendario_month.html', {'mes': mes, 'vevents': vevents})

        elif vista_actual == 'agenda':
            mes = relativedelta(months=1)
            m1 = calendar.Calendar().monthdatescalendar(fecha.year, fecha.month)
            m2 = calendar.Calendar().monthdatescalendar((fecha + mes).year, (fecha + mes).month)[1:]
            meses = m1 + m2
            vevents = vevents_agenda(g_e, fecha, meses)
            # vevents = Vevent.objects.filter(
            #     Q(subentidades__in=g_e.subentidades_hijos()) | Q(invitados__in=[g_e.gauser]) | Q(
            #         propietarios__in=[g_e.gauser]), dtend__gte=fecha,
            #     dtstart__lte=meses[-1][-1]).distinct()
            renderizado = render_to_string('calendario_agenda.html', {'vevents': vevents, 'meses': meses})

        elif request.POST['action'] == 'pdf_documentos':
            # eventos = Evento.objects.filter(
            #     Q(gauser_extra=g_e) | Q(subentidades__in=g_e.subentidades.all()) | Q(invitados__in=[g_e]))
            # fichero = 'Eventos_%s' % (request.session["gauser_extra"].gauser.username)
            # c = render_to_string('calendario2pdf.html',
            #                      {'calendario': calendario,
            #                       'eventos': eventos, }, request=request)
            # pdfkit ???
            # response = HttpResponse(fich, content_type='application/pdf')
            # response['Content-Disposition'] = 'attachment; filename=' + fichero + '.pdf'
            # return response
            pass
    else:
        try:
            fecha = datetime.strptime(request.GET['fecha'], '%d%m%Y')
        except:
            fecha = datetime.today()
        try:
            vista_actual = request.GET['v']
        except:
            vista_actual = 'month'
        if vista_actual == 'agenda':
            mes = relativedelta(months=1)
            m1 = calendar.Calendar().monthdatescalendar(fecha.year, fecha.month)
            m2 = calendar.Calendar().monthdatescalendar((fecha + mes).year, (fecha + mes).month)[1:]
            meses = m1 + m2
            vevents = vevents_agenda(g_e, fecha, meses)
            renderizado = render_to_string('calendario_agenda.html', {'vevents': vevents, 'meses': meses})
        else:
            mes = calendar.Calendar().monthdatescalendar(fecha.year, fecha.month)
            vevents = vevents_month(g_e, fecha)
            renderizado = render_to_string('calendario_month.html', {'mes': mes, 'vevents': vevents})

    return render(request, "base_calendario.html",
                  {
                      'iconos':
                          ({'tipo': 'button', 'nombre': 'check', 'texto': 'Aceptar', 'permiso': 'm30',
                            'title': 'Grabar el nuevo evento/acontecimiento'},
                           {'tipo': 'button', 'nombre': 'arrow-left', 'texto': 'Cancelar',
                            'title': 'Cancelar y volver a ver el calendario', 'permiso': 'm30'},
                           {'tipo': 'button', 'nombre': 'file-pdf-o', 'texto': 'PDF', 'permiso': 'm30',
                            'title': 'Genera documento PDF con tus eventos marcados en el calendario'},
                           ),
                      'formname': 'Calendario',
                      'avisos': Aviso.objects.filter(usuario=g_e, aceptado=False),
                      'renderizado': renderizado,
                      'vista_actual': vista_actual,
                      'fecha': fecha
                  })


class VeventForm(forms.ModelForm):
    class Meta:
        model = Vevent
        exclude = ('trans', 'propietario')


@login_required()
def edita_evento(request):
    g_e = request.session["gauser_extra"]
    vista_actual = request.GET['v']
    vevent = Vevent.objects.get(id=request.GET['vevent'], propietarios__in=[g_e.gauser])
    if request.method == 'POST':
        form = VeventForm(request.POST, instance=vevent)
        if form.is_valid():
            vevent = form.save()
            dtstart = datetime.strptime(request.POST['dtstart'], "%d/%m/%Y %H:%M")
            vevent.entidad = g_e.ronda.entidad
            if not vevent.dtend:
                vevent.dtend = datetime.combine(dtstart, datetime.max.time())
            else:
                vevent.dtend = datetime.strptime(request.POST['dtend'], "%d/%m/%Y %H:%M")
            vevent.dtstart = dtstart
            vevent.save()
            crear_aviso(request, True, "Se actualiza el evento con id %s" % (vevent.id))
            if request.POST['send_telegram'] == 'true':
                # Preparamos instrucciones para mandar un correo a los usuarios afectados
                try:
                    etiqueta = Etiqueta.objects.get(nombre='vevent' + str(vevent.id))
                except:
                    etiqueta = Etiqueta.objects.create(nombre='vevent' + str(vevent.id), propietario=g_e)
                asunto = u'Actualización del evento: ' + vevent.summary
                texto_html = render_to_string('evento_informar_mail.html',
                                              {'vevent': vevent, 'actualizador': g_e, 'tipo': 'Actualizado'})
                mensaje = Mensaje.objects.create(emisor=g_e, fecha=datetime.now(), asunto=asunto, mensaje=texto_html)
                mensaje.etiquetas.add(etiqueta)
                for g in vevent.invitados.all():
                    mensaje.receptores.add(g)
                for g in vevent.propietarios.all():
                    mensaje.receptores.add(g)
                for ge in Gauser_extra.objects.filter(ronda=g_e.ronda, subentidades__in=vevent.subentidades.all()):
                    mensaje.receptores.add(ge.gauser)
                crea_mensaje_cola(mensaje)
            if request.POST['send_correo'] == 'true':
                texto_telegram = render_to_string('evento_informar_telegram.html',
                                                  {'vevent': vevent, 'actualizador': g_e, 'tipo': 'Actualizado'})
                envia_telegram(g_e, texto_telegram, gausers=vevent.invitados.all(),
                               subentidades=vevent.subentidades.all())

calendario/templates/crea_evento.html
{% extends "base_select2-4.html" %}
{% load my_templatetags %}

{% block contenido %}
    <form action="" method="post" enctype="multipart/form-data" id="{{ formname }}" name="{{ formname }}"
          xmlns="http://www.w3.org/1999/html">
        {% csrf_token %}
        <input type="hidden" name="action" id="action" value="crear_evento">
        <input type="hidden" name="q" id="q" value="">
        <input type="hidden" name="page" id="page" value="">

        <div class="">
            <h4 style="text-align: center;color: #008CBA;"><strong> Creación de un nuevo evento</strong></h4>
        </div>

        <div class="row">
            <div class="columns large-8">
                <label> Nombre del evento
                    <input type="text" name="summary" maxlength="200" placeholder="Este campo es obligatorio">
{#                    {{ form.summary }}#}
                </label>
            </div>
            <div class="columns large-2" style="position: relative;">
                <label>
                    Enviar Telegram</label>
                <a id="a_telegram">No</a>
                <input name="send_telegram" type="hidden" value="no" id="send_telegram">
            </div>
            <div class="columns large-2" style="position: relative;">
                <label>
                    Enviar e-mail</label>
                <a id="a_correo">No</a>
                <input name="send_correo" type="hidden" value="false" id="send_correo">
            </div>
        </div>
        <div class="row">
            <div class="columns large-4">
                <label> Lugar
                    {{ form.location }}
                </label>
            </div>
            <div class="columns large-3" style="position: relative;">
                <label>
                    Inicio
                    <input type="datetime" name="dtstart" id="id_inicio"
                           value="{{ fecha|date:'d\/m\/Y H\:i' }}" placeholder="Este campo es obligatorio">
                </label>
            </div>
            <div class="columns large-3" style="position: relative;">
                <label>
                    Fin
                    <input type="datetime" name="dtend" id="id_fin" value="">
                </label>
            </div>
            <div class="columns large-2" style="position: relative;">
                <label>
                    Es festivo?
                </label>
                <a id="a_festivo">No</a>
                <input name="festivo" type="hidden" value="0" id="is_festivo">
            </div>
        </div>
        <div class="row">
            <div class="columns large-12">
                <label> Secciones/Departamentos invitadas al evento
                    <select multiple name="subentidades" id="id_subentidades">
                        {% for subentidad in subentidades %}
                            <option value="{{ subentidad.id }}">{{ subentidad.nombre }}</option>
                        {% endfor %}
                    </select>
                </label>
            </div>
        </div>
        <div class="row">
            <div class="columns large-12">
                <label> Cargos/Perfiles invitados al evento
                    <select multiple name="cargos" id="id_cargos">
                        {% for cargo in cargos %}
                            <option value="{{ cargo.id }}">{{ cargo.cargo }}</option>
                        {% endfor %}
                    </select>
                </label>
            </div>
        </div>
        <div class="row">
            <div class="columns large-12">
                <label> Introduce una descripción (opcional)
                    {{ form.description }}
                </label>
            </div>
        </div>
        <div class="row">
            <div class="columns large-12">
                <label title="Estas personas verán el evento en sus calendarios">
                    Personas que estan invitadas a este evento
                    <select multiple name="invitados" id="id_invitados">
                    </select>
                </label>
            </div>
        </div>
        <div class="row">
            <div class="columns large-12">
                <label title="Estas personas veran el evento en su calendario y lo podrán editar o borrar">
                    Personas propietarias de este evento
                    <select multiple name="propietarios" id="id_propietarios">
                        <option value="{{ request.session.gauser_extra.gauser.id }}" selected>
                            {{ request.session.gauser_extra.gauser.last_name }}, {{ request.session.gauser_extra.gauser.first_name }}
                        </option>
                    </select>
{#                    <input type="hidden" name="propietarios" value="{{ request.session.gauser_extra.gauser.id }}">#}
                </label>
            </div>
        </div>
    </form>

{% endblock %}


{% block final %}
    <script>
        {#        habilita(['h_check', 's_file-pdf-o', 'h_arrow-left']);#}
        habilita(['s_check', 'h_file-pdf-o', 's_arrow-left']);

        $("#id_inicio").fdatetimepicker({
            format: 'dd/mm/yyyy hh:ii',
            weekStart: 1
        });

        $('#id_fin').fdatetimepicker({
            format: 'dd/mm/yyyy hh:ii',
            weekStart: 1
        });

        $('#check_sign').click(function (e) {
            e.preventDefault();
            document.{{formname}}.submit();

        });
        $('#arrow-left_sign').click(function (e) {
            e.preventDefault();
            var fecha = $('#id_inicio').val().replace(/\//g,'').replace(/\s.*/g,'');
            window.location.href = "/calendario/?fecha=" + '{{ fecha }}' + '&v=' + '{{ vista_actual }}';
        });

        $('#id_subentidades').select2({placeholder: "Escribe parte del nombre para buscar coincidencias"});
        $('#id_cargos').select2({placeholder: "Escribe parte del nombre para buscar coincidencias"});

        $('#id_invitados,#id_propietarios').select2({
            placeholder: "Para buscar un registro, escribe parte del texto contenido en él",
            allowClear: true,
            ajax: {
                url: "/calendario_ajax/",
                type: 'POST',
                dataType: 'json',
                delay: 250,
                data: function (params) {
                    $('#q').val(params.term);
                    $('#page').val(params.page);
                    $('#action').val('buscar_invitados');
                    return $('#' + '{{ formname }}').serialize();
                },
                processResults: function (data, page) {
                    return {
                        results: $.map(data, function (item) {
                            return {
                                text: item.last_name + ', ' + item.first_name,
                                id: item.id
                            }
                        })
                    };
                },
                cache: true
            },
            escapeMarkup: function (markup) {
                return markup;
            }, // let our custom formatter work
            minimumInputLength: 3,
            language: {
                inputTooShort: function () {
                    return "Introduce al menos 3 caracteres para iniciar búsqueda";
                }
            }
        });

        $('#a_correo').click(function(e){
            e.preventDefault();
            var valor = $('#send_correo').val();
            if (valor == 'true'){
                $('#send_correo').val(false);
                $(this).html('No');
            } else {
                $('#send_correo').val(true);
                $(this).html('Sí');
            }
        });

        $('#a_telegram').click(function(e){
            e.preventDefault();
            var valor = $('#send_telegram').val();
            if (valor == 'true'){
                $('#send_telegram').val(false);
                $(this).html('No');
            } else {
                $('#send_telegram').val(true);
                $(this).html('Sí');
            }
        });

        $('#a_festivo').click(function(e){
            e.preventDefault();
            var valor = $('#is_festivo').val();
            if (valor == '1'){
                $('#is_festivo').val('0');
                $(this).html('No');
            } else {
                $('#is_festivo').val('1');
                $(this).html('Sí');
            }
        });
    </script>

{% endblock %}

calendario/templates/evento_informar.html
{% if vevent.dtend %}
    {% if vevent.dtstart == vevent.dtend %}
        <p>El {{ vevent.dtstart|date:'l\, j \d\e F \a \l\a\s H:i'|lower }}</p>
    {% elif vevent.dtstart|date:'dmY' == vevent.dtend|date:'dmY' %}
        <p>El {{ vevent.dtstart|date:'l\, j \d\e F, \d\e\s\d\e \l\a\s H:i'|lower }} hasta
            las {{ vevent.dtend|date:'H:i' }}</p>
    {% else %}
        <p>Desde el {{ vevent.dtstart|date:'l\, j \d\e F, \a \l\a\s H:i'|lower }} hasta
            el {{ vevent.dtend|date:'l\, j \d\e F, \a \l\a\s H:i'|lower }}</p>
    {% endif %}
{% else %}
    <p>El {{ vevent.dtstart|date:'l\, j \d\e F \a \l\a\s H:i'|lower }}</p>
{% endif %}
{% if vevent.location %}
    <p>Lugar: <b>{{ vevent.location }}</b></p>
{% endif %}
<p>
    {% autoescape off %}
        {{ vevent.description }}
    {% endautoescape %}
</p>
<hr>
{% if usuario == 'Propietario' %}
    <p class="radius alert label">Eres propietario de este evento. <br>Si lo eliminas se borrarán todas la invitaciones.
    </p>
{% elif usuario == 'Cargo' %}
    <p class="radius alert label">Tienes un cargo/perfil de primer nivel y puedes eliminar este evento. <br>Si lo
        eliminas se borrarán todas la invitaciones.</p>
{% elif usuario == 'Invitado' %}
    <p class="radius success label">Lees esto porque te han invitado personalmente a este evento. <br>Si lo eliminas se
        borrará únicamente tu invitación.</p>
{% else %}
    <p class="radius secondary label">Lees este evento porque perteneces a una sección o departamento al que fue
        inviado.</p>
{% endif %}

calendario/templates/evento_informar_telegram.html
{{ actualizador.gauser.get_full_name }} ha {% if tipo == 'Nuevo' %} creado un evento {% else %}actualizado el evento{% endif %} denominado: "{{ vevent.summary }}"
{% if vevent.dtend %}
    {% if vevent.dtstart == vevent.dtend %}
        Tendrá lugar el {{ vevent.dtstart|date:'l\, j \d\e F \a \l\a\s H:i'|lower }}
    {% elif vevent.dtstart|date:'dmY' == vevent.dtend|date:'dmY' %}
        Tendrá lugar el {{ vevent.dtstart|date:'l\, j \d\e F, \d\e\s\d\e \l\a\s H:i'|lower }} hasta las {{ vevent.dtend|date:'H:i' }}.
    {% else %}
        Se desarrollará desde el {{ vevent.dtstart|date:'l\, j \d\e F, \a \l\a\s H:i'|lower }} hasta el {{ vevent.dtend|date:'l\, j \d\e F, \a \l\a\s H:i'|lower }}.
    {% endif %}
{% else %}
    Comenzará el {{ vevent.dtstart|date:'l\, j \d\e F \a \l\a\s H:i'|lower }}.
{% endif %}
{% if vevent.location %}
    Lugar: {{ vevent.location }}
{% endif %}