vut/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

urlpatterns = [
    path('viviendas/', views.viviendas),
    path('ajax_viviendas/', views.ajax_viviendas),
    path('reservas_vut/', views.reservas_vut),
    path('ajax_reservas_vut/', views.ajax_reservas_vut),
    path('viajeros/', views.viajeros),
    path('contabilidad_vut/', views.contabilidad_vut),
    path('ajax_contabilidad_vut/', views.ajax_contabilidad_vut),
    path('domotica_vut/', views.domotica_vut),
    path('ajax_domotica_vut/', views.ajax_domotica_vut),
    path('viviendas_registradas_vut/', views.viviendas_registradas_vut),
    path('registro_viajero_manual/', views.registro_viajero_manual),
    path('web_vut/', views.web_vut),
    path('web_vut_id/<int:vivienda_id>/', views.web_vut_id),
    path('reserva_vut_crea_recibo/<int:reserva_id>/', views.reserva_vut_crea_recibo),
    path('rvpd/<str:secret_id>/', views.rvpd),
    path('contratos_vut/', views.contratos_vut),
    path('firconvut/<str:secret_id>/<str:n>/', views.firconvut),
    # path('web_vut_id/', views.web_vut_id),
    path('getvuts/<int:entidad_code>/', views.getvuts),
    path('verlibroregistros/<int:id_vivienda>/', views.verlibroregistros),
]

vut/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from PIL import Image
import random
import os

from django.db import models
from django.utils.timezone import now, timedelta
from django.core.files.storage import FileSystemStorage

from autenticar.models import Permiso, Gauser
from domotica.models import Dispositivo
from entidades.models import Entidad, Gauser_extra
from gauss.funciones import pass_generator

# Create your models here.

PAISES = (('A9401AAAAA', 'AFGANISTAN'), ('A9399AAAAA', 'AFRICA'), ('A9102AAAAA', 'ALBANIA'), ('A9103AAAAA', 'ALEMANIA'),
          ('A9299AAAAA', 'AMERICA'), ('A9133AAAAA', 'ANDORRA'), ('A9301AAAAA', 'ANGOLA'),
          ('A9255AAAAA', 'ANTIGUA BARBUDA'), ('A9200AAAAA', 'ANTILLAS NEERLANDESAS'), ('A9600AAAAA', 'APATRIDA'),
          ('A9403AAA1A', 'ARABIA SAUDITA'), ('A9304AAAAA', 'ARGELIA'), ('A9202AAAAA', 'ARGENTINA'),
          ('A9142AAAAA', 'ARMENIA'), ('A9257AAAAA', 'ARUBA'), ('A9499AAAAA', 'ASIA'), ('A9500AAAAA', 'AUSTRALIA'),
          ('A9104AAAAA', 'AUSTRIA'), ('A9143AAA2A', 'AZERBAYAN'), ('A9203AAAAA', 'BAHAMAS'), ('A9405AAAAA', 'BAHREIN'),
          ('A9432AAAAA', 'BANGLADESH'), ('A9205AAAAA', 'BARBADOS'), ('A9105AAAAA', 'BELGICA'), ('A9207AAAAA', 'BELICE'),
          ('A9407AAAAA', 'BHUTAN'), ('A9144AAAAA', 'BIELORRUSIA'), ('A9204AAAAA', 'BOLIVIA'),
          ('A9156AAAAA', 'BOSNIA HERZEGOVINA'), ('A9305AAAAA', 'BOTSWANA'), ('A9206AAAAA', 'BRASIL'),
          ('A9409AAAAA', 'BRUNEI'), ('A9134AAAAA', 'BULGARIA'), ('A9303AAAAA', 'BURKINA FASO'),
          ('A9321AAAAA', 'BURUNDI'), ('A9315AAAAA', 'CABO VERDE'), ('A9402AAAAA', 'CAMBOYA'), ('A9308AAAAA', 'CAMERUN'),
          ('A9208AAAAA', 'CANADA'), ('A9372AAAAA', 'CHAD'), ('A9106AAAAD', 'CHECOSLOVAQUIA'), ('A9210AAAAA', 'CHILE'),
          ('A9406AAAAA', 'CHINA'), ('A9107AAAAA', 'CHIPRE'), ('A9212AAAAA', 'COLOMBIA'), ('A9311AAAAA', 'COMORES'),
          ('A9460AAAAA', 'COREA NORTE'), ('A9410AAAAA', 'COREA SUR'), ('A9314AAAAA', 'COSTA MARFIL'),
          ('A9214AAAAA', 'COSTA RICA'), ('A9140AAAAA', 'CROACIA'), ('A9216AAAAA', 'CUBA'), ('A9258AAAAA', 'CURAÇAO'),
          ('A9108AAAAA', 'DINAMARCA'), ('A9317AAAAA', 'DJIBOUTI'), ('A9217AAAAA', 'DOMINICA'),
          ('A9222AAAAA', 'ECUADOR'), ('A9300AAAAA', 'EGIPTO'), ('A9429AAAAA', 'EMIRATOS ARABES UNIDOS'),
          ('A9384AAAAA', 'ERITREA'), ('A9158AAAAA', 'ESLOVAQUIA'), ('A9141AAAAA', 'ESLOVENIA'),
          ('A9109AAAAA', 'ESPAÑA'), ('A9525AAA1A', 'ESTADOS FEDERADOS MICRONESIA'),
          ('A9224AAA1A', 'ESTADOS UNIDOS AMERICA'), ('A9137AAAAA', 'ESTONIA'), ('A9318AAAAA', 'ETIOPIA'),
          ('A9199AAAAA', 'EUROPA'), ('A9396AAAAA', 'FERNANDO POO'), ('A9550AAAAA', 'FIDJI'),
          ('A9411AAAAA', 'FILIPINAS'), ('A9110AAAAA', 'FINLANDIA'), ('A9111AAAAA', 'FRANCIA'), ('A9320AAAAA', 'GABON'),
          ('A9323AAAAA', 'GAMBIA'), ('A9145AAAAA', 'GEORGIA'), ('A9322AAAAA', 'GHANA'), ('A9113AAAAA', 'GRECIA'),
          ('A9228AAAAA', 'GUATEMALA'), ('A9325AAA3A', 'GUINEA'), ('A9328AAA1A', 'GUINEA BISSAU'),
          ('A9324AAAAA', 'GUINEA ECUATORIAL'), ('A9225AAAAA', 'GUYANA'), ('A9230AAAAA', 'HAITI'),
          ('A9232AAAAA', 'HONDURAS'), ('A9462AAAAA', 'HONG KONG CHINO'), ('A9114AAAAA', 'HUNGRIA'),
          ('A9395AAAAA', 'IFNI'), ('A9412AAAAA', 'INDIA'), ('A9414AAAAA', 'INDONESIA'), ('A9413AAAAA', 'IRAK'),
          ('A9415AAAAA', 'IRAN'), ('A9115AAAAA', 'IRLANDA'), ('A9116AAAAA', 'ISLANDIA'),
          ('A9518AAAAA', 'ISLAS MARIANAS NORTE'), ('A9520AAAAA', 'ISLAS MARSHALL'), ('A9551AAA1A', 'ISLAS SALOMON'),
          ('A9417AAAAA', 'ISRAEL'), ('A9117AAAAA', 'ITALIA'), ('A9233AAAAA', 'JAMAICA'), ('A9416AAAAA', 'JAPON'),
          ('A9419AAAAA', 'JORDANIA'), ('A9465AAAAA', 'KAZAJSTAN'), ('A9336AAAAA', 'KENIA'), ('A9501AAAAA', 'KIRIBATI'),
          ('A9421AAAAA', 'KUWAIT'), ('A9418AAAAA', 'LAOS'), ('A9337AAAAA', 'LESOTHO'), ('A9138AAAAA', 'LETONIA'),
          ('A9423AAAAA', 'LIBANO'), ('A9342AAAAA', 'LIBERIA'), ('A9344AAAAA', 'LIBIA'), ('A9118AAAAA', 'LIECHTENSTEIN'),
          ('A9139AAAAA', 'LITUANIA'), ('A9119AAAAA', 'LUXEMBURGO'), ('A9463AAAAA', 'MACAO'),
          ('A9159AAAAA', 'MACEDONIA'), ('A9354AAAAA', 'MADAGASCAR'), ('A9425AAAAA', 'MALASIA'),
          ('A9346AAAAA', 'MALAWI'), ('A9436AAAAA', 'MALDIVAS'), ('A9347AAAAA', 'MALI'), ('A9120AAAAA', 'MALTA'),
          ('A9348AAAAA', 'MARRUECOS'), ('A9349AAAAA', 'MAURICIO'), ('A9350AAAAA', 'MAURITANIA'),
          ('A9234AAA1A', 'MEXICO'), ('A9148AAAAA', 'MOLDAVIA'), ('A9121AAAAA', 'MONACO'), ('A9427AAAAA', 'MONGOLIA'),
          ('A9160AAAAA', 'MONTENEGRO'), ('A9351AAAAA', 'MOZAMBIQUE'), ('A9400AAAAA', 'MYANMAR'),
          ('A9353AAAAA', 'NAMIBIA'), ('A9541AAAAA', 'NAURU'), ('A9420AAAAA', 'NEPAL'), ('A9236AAAAA', 'NICARAGUA'),
          ('A9360AAAAA', 'NIGER'), ('A9352AAAAA', 'NIGERIA'), ('A9122AAAAA', 'NORUEGA'),
          ('A9540AAAAA', 'NUEVA ZELANDA'), ('A9599AAAAA', 'OCEANIA'), ('A9444AAAAA', 'OMAN'),
          ('A9123AAA1A', 'PAISES BAJOS'), ('A9424AAA1A', 'PAKISTAN'), ('A9440AAAAA', 'PALESTINA'),
          ('A9238AAAAA', 'PANAMA'), ('A9542AAAAA', 'PAPUA NUEVA GUINEA'), ('A9240AAAAA', 'PARAGUAY'),
          ('A9242AAAAA', 'PERU'), ('A9124AAAAA', 'POLONIA'), ('A9125AAAAA', 'PORTUGAL'), ('A9244AAAAA', 'PUERTO RICO'),
          ('A9431AAAAA', 'QATAR'), ('A9112AAA1A', 'REINO UNIDO'), ('A9302AAA1A', 'REPUBLICA BENIN'),
          ('A9310AAA1A', 'REPUBLICA CENTROAFRICANA'), ('A9157AAAAA', 'REPUBLICA CHECA'),
          ('A9312AAA1A', 'REPUBLICA CONGO'), ('A9380AAAAA', 'REPUBLICA DEMOCRATICA CONGO'),
          ('A9218AAA1A', 'REPUBLICA DOMINICANA'), ('A9229AAAAA', 'REPUBLICA GRANADA'),
          ('A9466AAA1A', 'REPUBLICA KIRGUISTAN'), ('A9369AAAAA', 'REPUBLICA SUDAN SUR'), ('A9397AAAAA', 'RIO MUNI'),
          ('A9306AAAAA', 'RUANDA'), ('A9127AAAAA', 'RUMANIA'), ('A9149AAAAA', 'RUSIA'), ('A9398AAAAA', 'SAHARA'),
          ('A9256AAA1A', 'SAINT KITTS NEVIS'), ('A9220AAAAA', 'SALVADOR'), ('A9552AAAAA', 'SAMOA OCCIDENTAL'),
          ('A9135AAAAA', 'SAN MARINO'), ('A9259AAAAA', 'SAN MARTIN'), ('A9254AAA1A', 'SAN VICENTE GRANADINAS'),
          ('A9253AAAAA', 'SANTA LUCIA'), ('A9136AAA2A', 'SANTA SEDE'), ('A9361AAAAA', 'SANTO TOME PRINCIPE'),
          ('A9362AAAAA', 'SENEGAL'), ('A9155AAAAA', 'SERBIA'), ('A9363AAAAA', 'SEYCHELLES'),
          ('A9364AAAAA', 'SIERRA LEONA'), ('A9426AAAAA', 'SINGAPUR'), ('A9433AAAAA', 'SIRIA'),
          ('A9365AAAAA', 'SOMALIA'), ('A9404AAAAA', 'SRI LANKA'), ('A9367AAAAA', 'SUDAFRICA'), ('A9368AAAAA', 'SUDAN'),
          ('A9128AAAAA', 'SUECIA'), ('A9129AAAAA', 'SUIZA'), ('A9250AAAAA', 'SURINAM'), ('A9371AAAAA', 'SWAZILANDIA'),
          ('A9469AAAAA', 'TADJIKISTAN'), ('A9408AAA3A', 'TAIWAN TAIPEI'), ('A9370AAAAA', 'TANZANIA'),
          ('A9428AAAAA', 'THAILANDIA'), ('A9464AAAAA', 'TIMOR ORIENTAL'), ('A9374AAAAA', 'TOGO'),
          ('A9554AAAAA', 'TONGA'), ('A9245AAAAA', 'TRINIDAD TOBAGO'), ('A9378AAAAA', 'TUNEZ'),
          ('A9467AAAAA', 'TURKMENIA'), ('A9130AAAAA', 'TURQUIA'), ('A9560AAAAA', 'TUVALU'), ('A9152AAAAA', 'UCRANIA'),
          ('A9358AAAAA', 'UGANDA'), ('A9190AAA1A', 'UNION EUROPEA'), ('A9246AAAAA', 'URUGUAY'),
          ('A9468AAAAA', 'UZBEKISTAN'), ('A9565AAAAA', 'VANUATU'), ('A9248AAAAA', 'VENEZUELA'),
          ('A9430AAAAA', 'VIETNAM'), ('A9434AAAAA', 'YEMEN'), ('A9132AAAAD', 'YUGOSLAVIA'), ('A9382AAAAA', 'ZAMBIA'),
          ('A9357AAAAA', 'ZIMBABWE'))


class RemoteConection(models.Model):
    ip = models.URLField('URL desde la que se hace la conexión', blank=True, null=True)
    url = models.GenericIPAddressField('IP desde la que se hace la conexión', blank=True, null=True)
    ip2 = models.CharField('URL desde la que se hace la conexión', blank=True, null=True, max_length=30)
    url2 = models.CharField('IP desde la que se hace la conexión', blank=True, null=True, max_length=150)
    creado = models.DateTimeField("Fecha y hora en la que se produce la conexión", blank=True, null=True)

    def __str__(self):
        return '%s -- %s -- %s' % (self.creado, self.ip2, self.url2)


class Vivienda(models.Model):
    POL = (('PN', 'Policía Nacional'), ('GC', 'Guardia Civil'))
    propietario = models.ForeignKey(Gauser_extra, blank=True, null=True, on_delete=models.CASCADE,
                                    related_name='borrar')
    gpropietario = models.ForeignKey(Gauser, null=True, blank=True, on_delete=models.CASCADE, related_name='gborrar')
    propietarios = models.ManyToManyField(Gauser, blank=True)
    entidad = models.ForeignKey(Entidad, blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField("Nombre de la vivienda", blank=True, max_length=200, null=True)
    address = models.CharField("Dirección", blank=True, max_length=200, null=True)
    habitaciones = models.IntegerField("Número de habitaciones", blank=True, null=True)
    camas = models.IntegerField("Número de camas", blank=True, null=True)
    inquilinos = models.IntegerField("Número máximo de inquilinos", blank=True, null=True)
    iban = models.CharField("IBAN asociado a la vivienda", blank=True, max_length=50, null=True)
    nif = models.CharField("NIF del establecimiento", blank=True, max_length=50, null=True)
    municipio = models.CharField("Municipio del establecimiento", blank=True, max_length=150, null=True)
    provincia = models.CharField("Provincia del establecimiento", blank=True, max_length=150, null=True)
    observaciones = models.TextField("Observaciones sobre la vivienda", blank=True, null=True, default='')
    police = models.CharField("Selecciona el organismo policial", blank=True, max_length=5, choices=POL, default='')
    police_code = models.CharField("Código para web de la policía", blank=True, max_length=150, null=True, default='')
    police_pass = models.CharField("Password para web de la policía", blank=True, max_length=150, null=True, default='')
    borrada = models.BooleanField("Esta vivienda está borrada?", default=False)

vut/templates/correo_PN_GC.html
<p>Hola,</p>
{% if log == 'Correcto' %}
    <p>Se ha registrado correctamente en la web de la {{ viajero.reserva.vivienda.get_police_display }} el
    viajero:</p>
    <ul>
        <li>{{ viajero.nombre }} {{ viajero.apellido1 }} {{ viajero.apellido2 }}</li>
        <li>Vivienda: {{ viajero.reserva.vivienda }}</li>
        <li>Reserva ({{ viajero.reserva.get_portal_display }}): Entrada el {{ viajero.reserva.entrada }} y salida
            el {{ viajero.reserva.salida }}</li>
    </ul>
    <p>Información obtenida durante el proceso de registro:</p>
    <p>{{ viajero.observaciones }}</p>
{% elif log == 'Error1' %}
    <p>Se ha producido un error en la comunicación con la {{ viajero.reserva.vivienda.get_police_display }}.
        Se debe hacer el registro manualmente.</p>
    <p>Los datos del viajero con el que se ha producido el error son:</p>
    <ul>
        <li>{{ viajero.nombre }} {{ viajero.apellido1 }} {{ viajero.apellido2 }}</li>
        <li>Vivienda: {{ viajero.reserva.vivienda }}</li>
        <li>Reserva ({{ viajero.reserva.get_portal_display }}): Entrada el {{ viajero.reserva.entrada }} y salida
            el {{ viajero.reserva.salida }}</li>
    </ul>
    <p>Puedes encontrar más información en: GAUSS -> Viviendas Uso Turístico -> Reservas/Registro ->
        pestaña Ficheros Policía/Guardia Civil</p>
{% elif log == 'Error2' %}
    <p>Se ha producido un error al intentar entrar en la web de la
        {{ viajero.reserva.vivienda.get_police_display }}.</p>
    <p>Esto puede deberse a que los datos de usuario y contraseña definidos en GAUSS, para el acceso
        a la web de la {{ viajero.reserva.vivienda.get_police_display }} no sean correctos.</p>
    <p>Puedes modificar dicha información en: GAUSS -> Viviendas Uso Turístico -> Viviendas ->
        Selecciona tu vivienda</p>
    <p>Observaciones creadas sobre el viajero no registrado:</p>
    <p>{{ viajero.observaciones }}</p>
{% elif log == 'Error3' %}
    <p>Para que el registro de viajeros funcione debes indicar en qué organismo se produce dicho
        registro.</p>
    <p>Si tu vivienda está en una localidad con Policía Nacional, ese es el organismo que debes indicar.
        En otro caso debes hacerlo a través de la Guardia Civil.</p>
    <p>Puedes indicar dicha información en: GAUSS -> Viviendas Uso Turístico -> Viviendas ->
        Selecciona tu vivienda</p>
    <p>Observaciones creadas sobre el viajero no registrado:</p>
    <p>{{ viajero.observaciones }}</p>
    {% elif log == 'Error4' %}
    <p>Se ha producido un error en la última fase del registro. Debes hacer el registro del viajero
    manualmente.</p>
    <p>Observaciones creadas sobre el viajero no registrado:</p>
    <p>{{ viajero.observaciones }}</p>
{% endif %}

vut/templates/domotica_vut_accordion.html
{% load my_templatetags %}
{% load vut_extras %}
<dd class="accordion-navigation" id="accordion{{ vivienda.id }}"
    style="border-top: 1px dashed #ccc;{% if forloop.last %}border-bottom: 1px dashed #ccc;{% endif %}">
    <a href="#panel{{ vivienda.id }}">
        <i id="circle{{ vivienda.id }}" class="fa fa-plus-circle circle_icon"></i>
        <span id="span_vivienda_nombre{{ vivienda.id }}">{{ vivienda.nombre }}</span>
    </a>

    <div id="panel{{ vivienda.id }}" class="content accordion-vivienda" data-id="{{ vivienda.id }}">
    </div>
</dd>

vut/templates/registro_entrada_viajero_error.html
{% extends "base_empty.html" %}

{% block contenido %}
    {% if fechas %}
        <h4 style="text-align: center;color: #008CBA;"><strong>Este enlace no está activo en estos momentos.</strong>
        </h4>
        <h4 style="text-align: center;color: #008CBA;"><strong>Estará activo entre el {{ entrada }} y
            el {{ salida }}.</strong></h4>
    {% else %}
        <div>
            <h4 style="text-align: center;color: #008CBA;"><strong>Ha habido un error la página solicitada no
                existe</strong></h4>
            <p style="text-align: center;color: #008CBA; font-weight: 800;">Por favor, asegúrate de que has escrito bien
                la url en el navegador</p>
        </div>
    {% endif %}
{% endblock %}

{% block final %}
{% endblock %}



	

vut/templates/reservas_vut_registros_content.html
{% load vut_extras %}
{% if v.fichero_policia %}
    <div class="row">
        <div class="columns large-4">
            <label>Nombre:</label>{{ v.nombre }} {{ v.apellido1 }} {{ v.apellido2 }}
        </div>
        <div class="columns large-4">
            <label>Fecha de nacimiento:</label> {{ v.nacimiento|date:'d/m/Y' }}
        </div>
        <div class="columns large-4">
            <label>País de nacimiento:</label>{{ v.get_pais_display }}
        </div>
    </div>
    <br>
    <div class="row">
        <div class="columns large-4">
            <label>Tipo de documento:</label> {{ v.get_tipo_ndi_display }}
        </div>
        <div class="columns large-4">
            <label>Nº de documento:</label>{{ v.ndi }}
        </div>
        <div class="columns large-4">
            <label>Fecha de expedición:</label>{{ v.fecha_exp|date:'d/m/Y' }}
        </div>
    </div>
    <br>
    <div class="row">
        <div class="columns large-4">
            <label>Fecha de entrada:</label>{{ v.reserva.entrada|date:'d/m/Y' }}
        </div>
        <div class="columns large-4">
            <label>Sexo:</label> {{ v.get_sexo_display }}
        </div>
        <div class="columns large-4">
            <label>Registrado en {{ v.reserva.vivienda.get_police_display }}:</label>
            <div id="registro_policia{{ v.id }}">
                <span style="color:green"><i class="fa fa-check"></i> </span>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="columns large-12 text-center"><img src="{{ v.firma.url }}" width="120px"/>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="columns large-12"><label>Observaciones:</label>
            <div id="observaciones{{ v.id }}">{% autoescape off %}{{ v.observaciones }}{% endautoescape %}</div>
        </div>
    </div>
    {% with parte_pdf_PN=v|has_parte_pdf_PN %}
        {% if parte_pdf_PN %}
            <div class="row">
                <div class="columns large-12">
                    <a data-id="{{ parte_pdf_PN }}" class="parte_pdf_PN">Descargar el parte generado por la Policía
                        Nacional</a>
                </div>
            </div>
        {% endif %}
    {% endwith %}
{% else %}

    <div class="row">
        <div class="columns large-3">
            <label>Nombre:
                <input type="text" class="input_text" data-campo="nombre" data-id="{{ v.id }}" value="{{ v.nombre }}">
            </label>
        </div>
        <div class="columns large-3">
            <label>Primer Apellido:
                <input type="text" class="input_text" data-campo="apellido1" data-id="{{ v.id }}"
                       value="{{ v.apellido1 }}"> </label>
        </div>
        <div class="columns large-3">
            <label>Segundo Apellido:
                <input type="text" class="input_text" data-campo="apellido2" data-id="{{ v.id }}"
                       value="{{ v.apellido2 }}"> </label>
        </div>
        <div class="columns large-3">
            <label>Fecha de nacimiento:
                <input type="text" class="input_fecha" data-campo="nacimiento" data-id="{{ v.id }}"
                       value="{{ v.nacimiento|date:'d/m/Y' }}" id="nacimiento{{ v.id }}" readonly>
            </label>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="columns large-3">
            <label>País de nacimiento:
                <select data-campo="pais" data-id="{{ v.id }}" class="input_select">
                    <option value="{{ v.pais }}">{{ v.get_pais_display }}</option>
                    {% for p in paises %}
                        <option value="{{ p.0 }}">{{ p.1 }}</option>
                    {% endfor %}
                </select>
            </label>
        </div>
        <div class="columns large-3">
            <label>Tipo de documento:
                <select data-campo="tipo_ndi" data-id="{{ v.id }}" class="input_select">
                    <option value="{{ v.tipo_ndi }}">{{ v.get_tipo_ndi_display }}</option>
                    <option value="D">DNI</option>
                    <option value="P">Pasaporte</option>
                    <option value="C">Permiso de conducir</option>
                    <option value="I">Carta o documento de identidad extranjera</option>
                    <option value="X">Permiso de residencia de estado miembro de la UE</option>
                    <option value="N">NIE o tarjeta española de extranjeros</option>
                </select>
            </label>
        </div>
        <div class="columns large-3">
            <label>Nº de documento:
                <input type="text" class="input_text" data-campo="ndi" data-id="{{ v.id }}" value="{{ v.ndi }}">
            </label>
        </div>
        <div class="columns large-3">
            <label>Fecha de expedición:
                <input type="text" class="input_fecha" data-campo="fecha_exp" data-id="{{ v.id }}"
                       value="{{ v.fecha_exp|date:'d/m/Y' }}" id="fecha_exp{{ v.id }}" readonly>
            </label>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="columns large-4">
            <label><label>Fecha de entrada:</label>{{ v.reserva.entrada|date:'d/m/Y' }}</label>
        </div>
        <div class="columns large-4">
            <label>Sexo:
                <select data-campo="sexo" data-id="{{ v.id }}" class="input_select">
                    <option value="{{ v.sexo }}">{{ v.get_sexo_display }}</option>
                    <option value="F">Femenino</option>
                    <option value="M">Masculino</option>
                </select>
            </label>
        </div>
        <div class="columns large-4">
            <label>Registrado en {{ v.reserva.vivienda.get_police_display }}:</label>
            <div id="registro_policia{{ v.id }}">
                <a data-dropdown="drop{{ v.id }}" aria-controls="drop1" aria-expanded="false">Posibles
                    acciones</a>
                <ul id="drop{{ v.id }}" class="f-dropdown" data-dropdown-content aria-hidden="true"
                    tabindex="-1">
                    <li>
                        <a title="Selecciona esta opción si quieres que Gauss intente registrar automáticamente al viajero en la Policía/Guardia Civil"
                           data-id="{{ v.id }}" class="activar_registro"><i class="fa fa-vcard-o fa-fw"></i>
                            Intentar que Gauss registre al viajero</a></li>
                    <li><a data-id="{{ v.id }}" class="registrado_manualmente"
                           title="Selecciona esta opción si has registrado manualmente al viajero en la página web de la Policía/Guardia Civil">
                        <i class="fa fa-check fa-fw"></i>Marcar como registrado</a></li>
                </ul>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="columns large-12 text-center"><img src="{{ v.firma.url }}" width="120px"/>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="columns large-12"><label>Observaciones:</label>
            <div id="observaciones{{ v.id }}">
            <textarea class="input_text" data-campo="observaciones" data-id="{{ v.id }}">
                {% autoescape off %}{{ v.observaciones }}{% endautoescape %}
            </textarea>
            </div>
        </div>
    </div>

    <script>
        $("#fecha_exp{{ v.id }}").fdatepicker({
            format: 'dd/mm/yyyy',
            weekStart: 1,
            endDate: new Date(),
            startView: 'decade',
            leftArrow: '<<',
            rightArrow: '>>',
            language: 'es'
        });

        $("#nacimiento{{ v.id }}").fdatepicker({
            format: 'dd/mm/yyyy',
            weekStart: 1,
            endDate: new Date(),
            startView: 'decade',
            leftArrow: '<<',
            rightArrow: '>>',
            language: 'es'
        });
    </script>

{% endif %}

vut/templates/reservas_vut_table.html
{% for r in reservas %}
    {% include "tr_reserva.html" %}
{% endfor %}