convivencia/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

urlpatterns = [
    path('gestionar_conductas/', views.gestionar_conductas),
    path('gestionar_conductas_ajax/', views.gestionar_conductas_ajax),
    path('sancionar_conductas/', views.sancionar_conductas),
    path('sancionar_conductas_ajax/', views.sancionar_conductas_ajax),
    path('expediente_sancionador/', views.expediente_sancionador),
]

vut/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

urlpatterns = [
    path('viviendas/', views.viviendas),
    path('ajax_viviendas/', views.ajax_viviendas),
    path('reservas_vut/', views.reservas_vut),
    path('ajax_reservas_vut/', views.ajax_reservas_vut),
    path('viajeros/', views.viajeros),
    path('contabilidad_vut/', views.contabilidad_vut),
    path('ajax_contabilidad_vut/', views.ajax_contabilidad_vut),
    path('domotica_vut/', views.domotica_vut),
    path('ajax_domotica_vut/', views.ajax_domotica_vut),
    path('viviendas_registradas_vut/', views.viviendas_registradas_vut),
    path('registro_viajero_manual/', views.registro_viajero_manual),
    path('web_vut/', views.web_vut),
    path('web_vut_id/<int:vivienda_id>/', views.web_vut_id),
    path('reserva_vut_crea_recibo/<int:reserva_id>/', views.reserva_vut_crea_recibo),
    path('rvpd/<str:secret_id>/', views.rvpd),
    path('contratos_vut/', views.contratos_vut),
    path('firconvut/<str:secret_id>/<str:n>/', views.firconvut),
    # path('web_vut_id/', views.web_vut_id),
    path('getvuts/<int:entidad_code>/', views.getvuts),
    path('verlibroregistros/<int:id_vivienda>/', views.verlibroregistros),
]

convivencia/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime
import os

import unicodedata
from django.db import models
from autenticar.models import Permiso
from entidades.models import Entidad, Cargo, Gauser_extra
from django.template.defaultfilters import slugify
from django.utils import timezone


def update_fichero(instance, filename):
    # instance.fich_name = filename
    nombre = 'IS%s_%s.pdf' %(instance.sancionado.id, instance.id)
    return '/'.join(['convivencia', str(instance.sancionado.entidad.code), nombre])


TIPOS = (
    ('CNC', 'Contrarias a las normas de convivencia'),
    ('GPC', 'Gravemente perjudicales para la convivencia'),
    ('ROF', 'Contrarias a las normas del centro educativo'),
)


class ConfiguraConvivencia(models.Model):
    entidad = models.ForeignKey(Entidad, on_delete=models.CASCADE)
    caduca_cnc = models.IntegerField('Número de meses en los que caduca una conducta contraria', default=3)
    caduca_gpc = models.IntegerField('Número de meses en los que caduca una conducta grave', default=6)
    caduca_rof = models.IntegerField('Número de meses en los que caduca una conducta del ROF', default=3)
    expulsar_cnc = models.IntegerField('Número de conductas contrarias para habilitar expulsión', default=5)
    expulsar_gpc = models.IntegerField('Número de conductas graves para habilitar expulsión', default=1)
    expulsar_rof = models.IntegerField('Número de conductas ROF para habilitar expulsión', default=5)
    expulsar_inf = models.IntegerField('Número de informes sancionadores para habilitar expulsión', default=3)
    expediente_cnc = models.IntegerField('Número de conductas contrarias para habilitar expediente', default=17)
    expediente_inf = models.IntegerField('Número de informes sancionadores para habilitar expediente', default=12)

    def __str__(self):
        return u'%s -> caduca_cnc: %s - caduca_gpc: %s - caduca_rof: %s - expulsar_cnc: %s - expulsar_gpc: %s -' \
               u' expulsar_rof: %s - expulsar_inf: %s - expediente_cnc: %s - expediente_inf: %s - ' % (
                   self.entidad, self.caduca_cnc, self.caduca_gpc, self.caduca_rof, self.expulsar_cnc,
                   self.expulsar_gpc, self.expulsar_rof, self.expulsar_inf, self.expediente_cnc, self.expediente_inf)


class Sancion(models.Model):
    entidad = models.ForeignKey(Entidad, on_delete=models.CASCADE)
    norma = models.CharField('Normativa en la que se apoya', max_length=200, blank=True)
    sancion = models.TextField('Redacción de la sanción')
    tipo = models.CharField('Sanción aplicada a conducta:', max_length=30, choices=TIPOS, blank=True)
    expulsion = models.BooleanField('La sanción conlleva expulsión?', default=False)
    cargos = models.ManyToManyField(Cargo) #Este campo se puede eliminar. A partir de ahora se basa en permiso
    permiso = models.ForeignKey(Permiso, blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Sanciones'
        ordering = ['tipo', 'id']

    def __str__(self):
        return u'%s (%s)' % (self.sancion, self.entidad.name)


class Conducta(models.Model):
    entidad = models.ForeignKey(Entidad, on_delete=models.CASCADE)
    norma = models.CharField('Normativa en la que se apoya', max_length=200, blank=True)
    conducta = models.TextField('Redacción de la conducta')
    tipo = models.CharField('Tipo de conducta', max_length=30, choices=TIPOS, blank=True)
    prescribe = models.IntegerField('Número de días que tarda en prescribir la conducta', default=90)

    class Meta:
        verbose_name_plural = 'Conductas sancionables'
        ordering = ['tipo', 'id']

    def __str__(self):
        return u'%s (%s)' % (self.conducta, self.entidad.name)


class Informe_sancionador(models.Model):
    sancionado = models.ForeignKey(Gauser_extra, on_delete=models.CASCADE)
    sancionador = models.ForeignKey(Gauser_extra, related_name='sancionador', on_delete=models.CASCADE)
    fecha = models.DateField('Fecha de la conducta-sanción', null=True, blank=True)
    conductas = models.ManyToManyField(Conducta, blank=True)
    sanciones = models.ManyToManyField(Sancion, blank=True)
    texto_motivo = models.TextField('Motivo de la sanción', null=True, blank=True, default='')
    texto_sancion = models.TextField('Concreción de la sanción', null=True, blank=True, default='')
    fichero = models.FileField("Fichero informe sancionador", blank=True)
    texto_html = models.TextField('Código html generador del pdf', null=True, blank=True)
    fecha_inicio = models.DateField('Fecha de inicio de la expulsión', null=True, blank=True)
    fecha_fin = models.DateField('Fecha de fin de la expulsión', null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)
    fecha_incidente = models.DateField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = timezone.now()
        return super(Informe_sancionador, self).save(*args, **kwargs)

    @property
    def expulsion(self):
        return self.sanciones.filter(expulsion=True).count() > 0

    @property
    def is_coherente(self):
        c = False
        mensaje= ''
        t_conductas = self.conductas.all().values_list('tipo', flat=True)
        t_sanciones = self.sanciones.all().values_list('tipo', flat=True)

        for t_c in t_conductas:
            if t_c == 'CNC' or t_c == 'ROF':
                c = True if 'CNC' in t_sanciones else False
                if not c:
                    mensaje += '<li>Al seleccionar una conducta contraria, se debe asignar una sanción del mismo tipo.</li>'
            if t_c == 'GPC':
                c = True if 'GPC' in t_sanciones else False
                if not c:
                    mensaje += '<li>Al seleccionar una conducta grave, se debe asignar una sanción del mismo tipo.</li>'
        for t_s in t_sanciones:
            if t_s == 'CNC' or t_s == 'ROF':
                c = True if ('CNC' in t_conductas or 'ROF' in t_conductas) else False
                if not c:
                    mensaje += '<li>Al asignar una sanción contraria, se debe seleccionar una conducta del mismo tipo.</li>'
            if t_s == 'GPC':
                c = True if 'GPC' in t_conductas else False
                if not c:
                    mensaje += '<li>Al asignar una sanción grave, se debe seleccionar una conducta del mismo tipo.</li>'
        if t_conductas.all().count() == 0 or t_sanciones.all().count() == 0:
            mensaje += '<li>Debes seleccionar al menos una conducta y una sanción de las existentes en la lista.</li>'
        return c, mensaje

    class Meta:
        verbose_name_plural = 'Informes sancionadores (Informe_sancionador)'
        ordering = ['fecha_incidente']

    def __str__(self):
        return 'Informe sancionador a %s. Entidad: %s (%s)' % (
            self.sancionado, self.sancionado.ronda.entidad.name, self.sancionador)

class FechaExpulsion(models.Model):
    informe = models.ForeignKey(Informe_sancionador, on_delete=models.CASCADE)
    fecha = models.DateField('Día en el que el usuario está expulsado', null=True, blank=True)

    def __str__(self):
        return u'Informe sancionador a %s expulsado el día %s' % (self.informe.sancionado, self.fecha)

class Expulsar(models.Model):
    expulsado = models.ForeignKey(Gauser_extra, on_delete=models.CASCADE)
    expulsa = models.ForeignKey(Gauser_extra, related_name='redactor_sancion', on_delete=models.CASCADE)
    fecha = models.DateField('Fecha de emisión de la expulsión')
    fecha_inicio = models.DateField('Fecha de emisión de la expulsión')
    fecha_fin = models.DateField('Fecha de emisión de la expulsión')
    texto_adicional = models.TextField('Texto a adjuntar en la sanción', null=True, blank=True)
    texto_html = models.TextField('Código html generador del pdf', null=True, blank=True)
    # fichero = models.CharField('fichero (pdf)', max_length=200)
    # fichero = models.ForeignKey(ConvivenciaFile, related_name="informe_expulsar", blank=True, on_delete=models.CASCADE)
    fichero = models.FileField("Fichero de la expulsión", upload_to=update_fichero, blank=True)
    creado = models.DateField("Fecha de creación", auto_now_add=True)
    modificado = models.DateField("Fecha de modificación", auto_now=True)

    class Meta:
        verbose_name_plural = 'Expulsiones'

    def __str__(self):
        return 'Informe de expulsión a %s. Entidad: %s (%s)' % (
            self.expulsado, self.expulsado.ronda.entidad.name, self.expulsa)

convivencia/templates/accordion_conducta.html
<dd class="accordion-navigation" id="accordion_c{{ conducta.id }}"
    style="border-top: 1px dashed #ccc;{% if forloop.last %}border-bottom: 1px dashed #ccc;{% endif %}">
    <a href="#panel_c{{ conducta.id }}">
        <i id="circle_c{{ conducta.id }}" class="fa fa-plus-circle circle_icon"></i>
        <span id="span_conducta{{ conducta.id }}">{{ conducta.conducta|truncatechars:93 }}</span> <span
            id="span_tipo_c{{ conducta.id }}" title="{{ conducta.get_tipo_display }}"
            style="color: #a3a3a3">{{ conducta.tipo }}</span>
    </a>

    <div id="panel_c{{ conducta.id }}" class="content accordion-conducta" data-id="{{ conducta.id }}">
    </div>
</dd>

convivencia/templates/accordion_sancion.html
<dd class="accordion-navigation" id="accordion_s{{ sancion.id }}"
    style="border-top: 1px dashed #ccc;{% if forloop.last %}border-bottom: 1px dashed #ccc;{% endif %}">
    <a href="#panel_s{{ sancion.id }}">
        <i id="circle_s{{ sancion.id }}" class="fa fa-plus-circle circle_icon"></i>
        <span id="span_sancion{{ sancion.id }}">{{ sancion.sancion|truncatechars:43 }}</span> <span
            id="span_tipo_s{{ sancion.id }}"
            style="color: #a3a3a3">{{ sancion.get_tipo_display }}</span>
    </a>

    <div id="panel_s{{ sancion.id }}" class="content accordion-sancion" data-id="{{ sancion.id }}">
    </div>
</dd>

convivencia/templates/formulario_sancion.html
{% load my_templatetags %}

<style>
    h4 {
        text-align: center;
        color: #008CBA;
    }

    .heading {
        color: #008cba;
        font-size: 0.85rem !important;
        font-weight: bold;
        text-transform: uppercase;
    }

    .heading_number {
        color: #008cba;
        font-size: 0.85rem !important;
        font-weight: bold;
        text-transform: uppercase;
        text-align: right;
    }
</style>
{% if gauser_extra|has_permiso:'borra_sanciones_tipificadas' %}
    <div class="row">
        <div class="large-9 medium-6 small-3 columns">
            &nbsp;
        </div>
        <div class="large-3 medium-6 small-9 columns" style="text-align: right;">
            <a class="button del_sancion" data-sancion="{{ sancion.id }}"><i class="fa fa-trash-o"></i> Borrar</a>
        </div>
    </div>
{% endif %}
<div class="row">
    <div class="large-4 columns">
        {% if gauser_extra|has_permiso:'edita_sanciones_tipificadas' %}
            <label title="Tipos de sanciones en función de la conducta contraria">Tipo
                <select id="id_tipo" name="tipo" data-sancion="{{ sancion.id }}">
                    <option value="CNC" {% if sancion.tipo == 'CNC' %}selected{% endif %}>Contraria a las normas de
                        convivencia
                    </option>
                    <option value="GPC" {% if sancion.tipo == 'GPC' %}selected{% endif %}>Gravemente perjudical para la
                        convivencia
                    </option>
                    <option value="ROF" {% if sancion.tipo == 'ROF' %}selected{% endif %}>Contraria a las normas del
                        centro educativo
                    </option>
                </select>
            </label>
        {% else %}
            <label title="Tipos de sanciones en función de la conducta contraria">Tipo
            </label>
            {{ sancion.get_tipo_display }}
        {% endif %}
    </div>
    <div class="large-6 columns">
        {% if gauser_extra|has_permiso:'edita_sanciones_tipificadas' %}
            <label>Normativa en la que se apoya
                <input id="id_norma_s" maxlength="200" name="norma_s" type="text"
                       data-sancion="{{ sancion.id }}" value="{{ sancion.norma }}">
            </label>
        {% else %}
            <label>Normativa en la que se apoya
            </label>
            {{ sancion.norma }}
        {% endif %}
    </div>
    <div class="large-2 columns">
        {% if gauser_extra|has_permiso:'edita_sanciones_tipificadas' %}
            <label>Conlleva expulsión</label>
            <a class="conlleva_expulsion" data-sancion="{{ sancion.id }}" id="conlleva_expulsion{{ sancion.id }}">
                {% if sancion.expulsion %}Sí{% else %}No{% endif %}</a>
        {% else %}
            <label>Conlleva expulsión
            </label>
            {% if sancion.expulsion %}Sí{% else %}No{% endif %}
        {% endif %}
    </div>
</div>
<div class="row">
    <div class="large-12 columns">
        {% if gauser_extra|has_permiso:'edita_sanciones_tipificadas' %}
            <label>Define la sancion
                <textarea id="id_sancion" name="sancion" rows="4"
                          data-sancion="{{ sancion.id }}">{{ sancion.sancion }}</textarea>
            </label>
        {% else %}
            <label>Define la sancion
            </label>
            {{ sancion.sancion }}
        {% endif %}
    </div>
</div>
{#<div class="row">#}
{#    <div class="large-12 columns">#}
{#        <label>Cargos que pueden imponer esta sanción#}
{#            {% if gauser_extra|has_permiso:'edita_sanciones_tipificadas' %}#}
{#                <select id="cargos_sancion{{ sancion.id }}" multiple data-sancion="{{ sancion.id }}">#}
{#                    {% for cargo in cargos %}#}
{#                        <option value="{{ cargo.id }}"#}
{#                                {% if cargo in sancion.cargos.all %}selected{% endif %}>{{ cargo.cargo }}</option>#}
{#                    {% endfor %}#}
{#                </select>#}
{#            {% else %}#}
{#                <span style="font-weight: 800;">{% for cargo in sancion.cargos.all %}#}
{#                    {{ cargo.cargo }}, {% endfor %}</span>#}
{#            {% endif %}#}
{#        </label>#}
{#    </div>#}
{#</div>#}

<div class="row">
    <div class="large-12 columns">
        <label><b>Cargo necesario para imponer esta sanción:</b><br>
            {% if gauser_extra|has_permiso:'edita_sanciones_tipificadas' %}
                <input type="radio" class="permiso_sancion" name="permiso_sancion" value="sancionar_nivel_director"
                       data-id="{{ sancion.id }}"
                       {% if sancion.permiso.code_nombre == 'sancionar_nivel_director' %}checked{% endif %}> Director
                &nbsp;&nbsp;&nbsp;
                <input type="radio" class="permiso_sancion" name="permiso_sancion" value="sancionar_nivel_jefe_estudios"
                       data-id="{{ sancion.id }}"
                       {% if sancion.permiso.code_nombre == 'sancionar_nivel_jefe_estudios' %}checked{% endif %}> Jefe
                de estudios &nbsp;&nbsp;&nbsp;
                <input type="radio" class="permiso_sancion" name="permiso_sancion" value="sancionar_nivel_tutor"
                       data-id="{{ sancion.id }}"
                       {% if sancion.permiso.code_nombre == 'sancionar_nivel_tutor' %}checked{% endif %}> Tutor &nbsp;
                &nbsp;&nbsp;
                <input type="radio" class="permiso_sancion" name="permiso_sancion" value="sancionar_nivel_docente"
                       data-id="{{ sancion.id }}"
                       {% if sancion.permiso.code_nombre == 'sancionar_nivel_docente' %}checked{% endif %}> Profesor
            {% else %}
                <span style="font-weight: 800;">{{ sancion.permiso.nombre }}</span>
            {% endif %}
        </label>
    </div>
</div>

<script>
    {% if gauser_extra|has_permiso:'borra_sanciones_tipificadas' %}
        $('#Contenido').on('click', '.del_sancion', function (e) {
            e.preventDefault();
            var sancion = $(this).data('sancion');
            $.post("/gestionar_conductas_ajax/", {action: 'del_sancion', sancion: sancion}, function (data) {
                if (data['ok']) {
                    $('#accordion_s' + data['sancion']).remove();
                    $("#update_ok").show().delay(1500).fadeOut();
                } else {
                    $("#update_error").show().delay(1500).fadeOut();
                }

            });
        });
    {% endif %}

    {% if gauser_extra|has_permiso:'edita_sanciones_tipificadas' %}
        $('#Contenido').on('click', '.conlleva_expulsion', function () {
            var sancion = $(this).data('sancion');
            $.post("/gestionar_conductas_ajax/", {action: 'conlleva_expulsion', 'sancion': sancion}, function (data) {
                if (data['ok']) {
                    $('#conlleva_expulsion' + data['sancion']).text(data['texto']);
                    $("#update_ok").show().delay(1500).fadeOut();
                } else {
                    $("#update_error").show().delay(1500).fadeOut();
                }
            });
        });

        $('#Contenido').on('keyup', '#id_sancion', function () {
            var texto = $(this).val();
            var sancion = $(this).data('sancion');
            $.post("/gestionar_conductas_ajax/", {
                action: 'change_texto_sancion',
                sancion: sancion,
                texto: texto
            }, function (data) {
                if (data['ok']) {
                    $('#span_sancion' + sancion).html(data['texto']);
                    $("#update_ok").show().delay(1500).fadeOut();
                } else {
                    $("#update_error").show().delay(1500).fadeOut();
                }
            });
        });

        $('#Contenido').on('change', '#id_tipo', function () {
            var tipo = $(this).val();
            var sancion = $(this).data('sancion');
            $.post("/gestionar_conductas_ajax/", {
                action: 'change_tipo_sancion',
                sancion: sancion,
                tipo: tipo
            }, function (data) {
                if (data['ok']) {
                    $('#span_tipo_s' + sancion).html(data['tipo']);
                    $("#update_ok").show().delay(1500).fadeOut();
                } else {
                    $("#update_error").show().delay(1500).fadeOut();
                }
            });
        });

        $('#Contenido').on('keyup', '#id_norma_s', function () {
            var texto = $(this).val();
            var sancion = $(this).data('sancion');
            $.post("/gestionar_conductas_ajax/", {
                action: 'change_texto_norma_s',
                sancion: sancion,
                texto: texto
            }, function (data) {
                if (data['ok']) {
                    $("#update_ok").show().delay(1500).fadeOut();
                } else {
                    $("#update_error").show().delay(1500).fadeOut();
                }
            });
        });

        $("#cargos_sancion{{ sancion.id }}").select2();
        $("body").on('change', '#cargos_sancion{{ sancion.id }}', function () {
            var sancion = $(this).data('sancion');
            var cargos = new Array();
            $('#cargos_sancion{{ sancion.id }}').each(function () {
                cargos.push($(this).val());
            });
            $.post("/gestionar_conductas_ajax/", {
                action: 'change_cargos_s',
                sancion: sancion,
                cargos: cargos
            }, function (data) {
                if (data['ok']) {
                    $("#update_ok").show().delay(1500).fadeOut();
                } else {
                    $("#update_error").show().delay(1500).fadeOut();
                }
            });
        });
    {% endif %}

    {% if gauser_extra|has_permiso:'edita_sanciones_tipificadas' %}
        $('#Contenido').on('change', '.permiso_sancion', function () {
            var permiso = $(this).val();
            var sancion = $(this).data('id');
            $.post("/gestionar_conductas_ajax/", {
                permiso: permiso, action: 'change_permiso_sancion',
                sancion: sancion
            }, function (data) {
                $("#update_ok").show().delay(1500).fadeOut();
            }, 'json');
        });
    {% endif %}
</script>

convivencia/templates/informe_sancionador_mail.html
{% load convivencia_extras %}
Alumno: <strong> {{ informe.sancionado.gauser.get_full_name }}</strong>
<br/>
Grupo: <strong> {{ informe.sancionado.gauser_extra_estudios.grupo.nombre }}</strong> (
{% for curso in informe.sancionado.gauser_extra_estudios.grupo.cursos.all %}{{ curso.nombre }}{% if not forloop.last %},
    &nbsp;{% endif %}{% endfor %})
<br/>
Tutor: <strong> {{ informe.sancionado.gauser_extra_estudios.tutor.gauser.get_full_name }}</strong>
<br>
Sancionado por: <strong>{% if dire %}{{ dire.gauser.get_full_name }}{% else %}
    {{ informe.sancionador.gauser.get_full_name }}{% endif %}</strong>

{% if informe.texto_motivo %}
    <p>El comportamiento  {% if informe.sancionado.gauser.sexo == 'H' %} del alumno, {% else %} de la alumna, {% endif %}
    ha sido: </p>
    <i>
        {% autoescape off %}
            {{ informe.texto_motivo }}
        {% endautoescape %}
    </i>
{% endif %}
<p> {% if informe.conductas.all|length > 1 %} Conductas contrarias a la convivencia: {% else %}
    Conducta contraria a la convivencia: {% endif %}</p>
<ul>
    {% for conducta in informe.conductas.all %}
        <li style="margin-bottom: 1em;"><strong> {{ conducta.conducta }} </strong></li>
    {% endfor %}
</ul>

<p> {% if informe.sanciones.all|length > 1 %} Medidas correctoras: {% else %} Medida correctora: {% endif %} </p>

<ul>
    {% for sancion in informe.sanciones.all %}
        <li style="margin-bottom: 1em;"><strong> {{ sancion.sancion }} </strong></li>
    {% endfor %}
</ul>

{% if informe.fechaexpulsion_set.all|length > 0 %}
    <p><strong> Se suspende el derecho de asistencia a clase del alumno
        {% if informe.fechaexpulsion_set.all|length == 1 %} el día: {% else %}los días:{% endif %}<br>
        {% for fecha in informe.fechaexpulsion_set.all %}
            {% if forloop.revcounter0 == 1 %}{{ fecha.fecha|date:"d/m/Y" }} y
                {% elif forloop.revcounter0 > 1 %}{{ fecha.fecha|date:"d/m/Y" }},
                {% else %}{{ fecha.fecha|date:"d/m/Y" }}
            {% endif %}
        {% endfor %}
    </strong></p>
    <p>Con el fin de que {% if informe.sancionado.gauser.sexo == 'H' %}el alumno{% else %}la alumna{% endif %}
        no interrumpa su proceso formativo, los profesores le proporcionarán tarea para ser realizada en casa.</p>
{% endif %}

{% if listar_conductas %}
    <p>Los informes sancionadores emitidos hasta el momento son:</p>
    {% for informe_sancionador in informes %}
        <p style="font-style:italic;"><strong> Informe emitido el {{ informe_sancionador.fecha_incidente|date:"d" }}
            de {{ informe_sancionador.fecha_incidente|date:"F" }}
            de {{ informe_sancionador.fecha_incidente|date:"Y" }}</strong></p>
        <ul>
            {% for conducta in informe.conductas.all %}
                <li>{{ conducta.conducta }}</li>
            {% endfor %}
        </ul>
    {% endfor %}

    {% if expulsiones|length > 1 %}
        <p>{{ informe.sancionado.gauser.get_full_name }} ha sido
            {% if informe.sancionado.gauser.sexo == 'H' %} expulsado, {% else %} expulsada, {% endif %}
            {{ expulsiones|length }} ve{{ expulsiones|length|pluralize:"z,ces" }}:</p>
        <ul>
            {% for expulsion in expulsiones %}
                <li>El {{ expulsion.fecha_incidente|date:"j" }} de {{ expulsion.fecha_incidente|date:"F" }}
                    de {{ expulsion.fecha_incidente|date:"Y" }}. {% if expulsion.fechaexpulsion_set.all|length > 0 %}
                        Días:
                        {% for fecha in expulsion.fechaexpulsion_set.all %}{% if forloop.revcounter0 == 1 %}
                            {{ fecha.fecha|date:"d/m/Y" }} y
                            {% elif forloop.revcounter0 > 1 %}{{ fecha.fecha|date:"d/m/Y" }}, {% else %}
                            {{ fecha.fecha|date:"d/m/Y" }}{% endif %}{% endfor %}{% endif %}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endif %}


{% with estadistica=informe.sancionado|estadistica_informes_is2pdf %}
    <p>{{ informe.sancionado.gauser.get_full_name }} tiene {{ estadistica.tcnc }}
        {% if estadistica.tcnc != 1 %} conductas contrarias {% else %}
            conducta contraria {% endif %} a la convivencia y {{ estadistica.gpc }} {% if estadistica.gpc != 1 %}
            conductas gravemente
            perjudiciales {% else %} conducta gravemente perjudicial {% endif %} para la convivencia, por las cuales se
        le han emitido {{ estadistica.informes }} informes sancionadores (incluido éste).</p>
{% endwith %}

 

convivencia/templates/informe_sancionador_mail_asunto.html
{% load convivencia_extras %}Informe sancionador para {{ informe.sancionado.gauser.get_full_name }} {{ informe.sancionado.gauser_extra_estudios.grupo.nombre }} ({% with estadistica=informe.sancionado|estadistica_informes_is2pdf %}CC: {{ estadistica.tcnc }}, CG: {{ estadistica.gpc }}, Informes: {{ estadistica.informes }}{% endwith %})

convivencia/templates/lista_de_conductas.html
<table>
    <tbody>
    {% for conducta in conductas %}
        <tr>
            <td><input type="checkbox" data-id="{{ conducta.id }}"
                       class="conductas_checkbox {{ conducta.tipo }}"
                       data-inf_actual="{{ inf_actual.id }}" data-tipo="{{ conducta.tipo }}"
                       {% if conducta in inf_actual.conductas.all %}checked="checked"{% endif %}></td>
            <td>{{ conducta.conducta }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

convivencia/templates/lista_de_sanciones.html
{% load convivencia_extras %}
<table>
    <tbody>
    {% for sancion in sanciones %}
        <tr>
{#            {% if sancionador|has_any_cargo:sancion.cargos.all or sancionador|has_permiso:'aplica_cualquier_sancion' %}#}
                {% if sancionador|has_permiso:sancion.permiso.code_nombre or sancionador|has_permiso:'aplica_cualquier_sancion' %}
                <td><input type="checkbox" id="s{{ sancion.id }}" data-id="{{ sancion.id }}"
                           data-inf_actual="{{ inf_actual.id }}" data-tipo="{{ sancion.tipo }}"
                           class="sanciones_checkbox {{ sancion.tipo }}"
                           {% if sancion in inf_actual.sanciones.all %}checked="checked"{% endif %}></td>
                <td>{{ sancion.sancion }}</td>
            {% else %}
                <td title="{{ sancionador.gauser.get_full_name }} no tiene permiso para imponer esta sanción. Pregunta en Jefatura de Estudios o Dirección si crees que se debería imponer esta sanción.">
                    <input type="checkbox" disabled></td>
                <td>{{ sancion.sancion }}</td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>