cupo/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

urlpatterns = [
    path('cupo/', views.cupo),
    path('ajax_cupo/', views.ajax_cupo),
    path('edit_cupo/<int:cupo_id>/', views.edit_cupo),
    path('plantilla_organica/', views.plantilla_organica),
    path('comprueba_dnis/', views.comprueba_dnis),
    path('arregla_duplicados/', views.arregla_duplicados),
    # path('select_po/', views.select_po),
    path('rrhh_cupos/', views.rrhh_cupos),
    path('estadistica_cupos/', views.estadistica_cupos),
]

vut/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

urlpatterns = [
    path('viviendas/', views.viviendas),
    path('ajax_viviendas/', views.ajax_viviendas),
    path('reservas_vut/', views.reservas_vut),
    path('ajax_reservas_vut/', views.ajax_reservas_vut),
    path('viajeros/', views.viajeros),
    path('contabilidad_vut/', views.contabilidad_vut),
    path('ajax_contabilidad_vut/', views.ajax_contabilidad_vut),
    path('domotica_vut/', views.domotica_vut),
    path('ajax_domotica_vut/', views.ajax_domotica_vut),
    path('viviendas_registradas_vut/', views.viviendas_registradas_vut),
    path('registro_viajero_manual/', views.registro_viajero_manual),
    path('web_vut/', views.web_vut),
    path('web_vut_id/<int:vivienda_id>/', views.web_vut_id),
    path('reserva_vut_crea_recibo/<int:reserva_id>/', views.reserva_vut_crea_recibo),
    path('rvpd/<str:secret_id>/', views.rvpd),
    path('contratos_vut/', views.contratos_vut),
    path('firconvut/<str:secret_id>/<str:n>/', views.firconvut),
    # path('web_vut_id/', views.web_vut_id),
    path('getvuts/<int:entidad_code>/', views.getvuts),
    path('verlibroregistros/<int:id_vivienda>/', views.verlibroregistros),
]

cupo/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import logging
from django.db import models
from django.db.models import Q
from django.utils.timezone import now

from gauss.constantes import CARGOS_CENTROS
from cupo.habilitar_permisos import Miembro_Equipo_Directivo
from gauss.funciones import pass_generator, genera_nie, usuarios_ronda
from autenticar.models import Gauser, Permiso, Menu_default
from entidades.models import Subentidad, Entidad, Ronda, Cargo, Gauser_extra, Dependencia, MiembroDepartamento, Menu, \
    EspecialidadDocenteBasica, MiembroEDB
from entidades.models import Departamento as DepEntidad
from entidades.menus_entidades import Menus_Centro_Educativo, TiposCentro
from estudios.models import Materia, Curso, Grupo, EtapaEscolar
from horarios.models import Actividad, Horario, Sesion, SesionExtra
from mensajes.models import Aviso
from programaciones.models import Departamento, Especialidad_entidad
from math import ceil
from cupo.tipos_centro import TC

logger = logging.getLogger('django')


class Cupo(models.Model):
    ronda = models.ForeignKey(Ronda, blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField("Nombre de la versión del cupo", max_length=150)
    bloqueado = models.BooleanField("¿Está bloqueado?", default=False)
    pub_rrhh = models.BooleanField("¿Se publica para RRHH?", default=False)
    creado = models.DateField("Fecha de creación", auto_now_add=True)
    modificado = models.DateField("Fecha de modificación", auto_now=True)

    class Meta:
        verbose_name_plural = 'Cupos de profesorado'
        ordering = ['-creado']

    def puede_activarse_pub_rrhh(self, g_e):
        try:
            msg = ''
            cargo_inspector = Cargo.objects.get(entidad=self.ronda.entidad, clave_cargo='g_inspector_educacion')
            # gauser_inspectores = usuarios_ronda(self.ronda, cargos=[cargo_inspector]).values_list('gauser__id', flat=True)
            ges_inspectores = Gauser_extra.objects.filter(ronda=self.ronda, cargos__in=[cargo_inspector])
            gauser_inspectores = ges_inspectores.values_list('gauser__id', flat=True)
            con1 = g_e.gauser.id in gauser_inspectores
            con2 = (self.ronda.entidad == g_e.ronda.entidad) and g_e.has_permiso('publica_cupo_para_rrhh')
            if con1 or con2:
                interinos = Profesor_cupo.objects.filter(profesorado__cupo=self, tipo='INT')
                q1 = Q(profesorado__especialidad__cod_espec='')
                q2 = Q(profesorado__especialidad__cod_cuerpo='')
                interinos_condiciones = interinos.filter(q1 | q2).distinct()
                if interinos_condiciones.count() == 0:
                    if self.bloqueado:
                        return True, 'Se cumplen todas las condiciones.'
                    else:
                        return False, 'El cupo debe estar bloqueado para activar la publicación.'
                else:
                    msg += 'Existen interinos sin código de especialidad y/o cuerpo: '
                    especialidades = []
                    for ic in interinos_condiciones:
                        if ic.profesorado.especialidad.nombre not in especialidades:
                            especialidades.append(ic.profesorado.especialidad.nombre)
                            # msg += ' %s - %s.' % (ic.profesorado.especialidad.nombre, ic.nombre)
                    msg += ' - '.join(especialidades)
                    # msg += '. No es posible la publicación.'
                    return False, msg
            else:
                msg = 'gauser: %s - inspectores: %s' % (g_e.gauser.id, ', '.join([str(i) for i in gauser_inspectores]))
                return False, 'No tiene permisos suficientes. con1: %s, con2: %s. %s' % (con1, con2, msg)
        except Exception as msg:
            return False, 'Error en la comprobación de permisos: %s' % str(msg)

    @property
    def es_posible_pdf_rrhh(self):
        return self.bloqueado and self.pub_rrhh

    @property
    def solicitud_interinos(self):
        return Profesor_cupo.objects.filter(profesorado__cupo=self, tipo='INT')

    @property
    def curso_escolar_cupo(self):
        y = self.ronda.fin.year
        return "%s/%s" % (y, y + 1)

    def __str__(self):
        return '%s %s (%s)' % (self.ronda.entidad.name, self.nombre, self.modificado)


class CupoPermisos(models.Model):
    PERMISOS = (('plwx', 'Propietario'), ('l', 'Lectura'), ('lw', 'Escritura'), ('lwx', 'Escritura y borrado'))
    cupo = models.ForeignKey(Cupo, on_delete=models.CASCADE)
    gauser = models.ForeignKey(Gauser, on_delete=models.CASCADE)
    permiso = models.CharField('Tipo de permiso', default='l', max_length=5, choices=PERMISOS)

    def __str__(self):
        return '%s %s (%s)' % (self.cupo, self.gauser, self.get_permiso_display())


class EspecialidadCupo(models.Model):
    cupo = models.ForeignKey(Cupo, on_delete=models.CASCADE)
    nombre = models.CharField("Nombre de la especialidad", max_length=150)
    # departamento = models.ForeignKey(Departamento, blank=True, null=True, on_delete=models.CASCADE)
    cod_espec = models.CharField("Código de especialidad", max_length=15, blank=True, null=True, default='')
    cod_cuerpo = models.CharField("Código del cuerpo", max_length=15, blank=True, null=True, default='')
    clave_ex = models.CharField("Clave externa", max_length=15, blank=True, null=True)
    dep = models.CharField('Departamento', max_length=310, blank=True, null=True, default='')
    x_dep = models.CharField('Departamento clave', max_length=9, blank=True, null=True, default='')
    max_completa = models.FloatField("Máximo número de periodos lectivos con jornada completa", default=20)
    min_completa = models.FloatField("Mínimo número de periodos lectivos con jornada completa", default=18)
    max_dostercios = models.FloatField("Máximo número de periodos lectivos con 2/3 de jornada", default=13)
    min_dostercios = models.FloatField("Mínimo número de periodos lectivos con 2/3 de jornada", default=12)
    max_media = models.FloatField("Máximo número de periodos lectivos con media jornada", default=10)
    min_media = models.FloatField("Mínimo número de periodos lectivos con media jornada", default=9)
    max_tercio = models.FloatField("Máximo número de periodos lectivos con 1/3 de jornada", default=7)
    min_tercio = models.FloatField("Mínimo número de periodos lectivos con 1/3 de jornada", default=6)
    observaciones = models.TextField('Observaciones', blank=True, null=True, default='')

    @property
    def nombre_oficial(self):
        try:
            return ESPECS[self.cod_cuerpo][self.cod_espec]
        except Exception as msg:
            return '%s - Error %s. Debe editarse' % (self.nombre, str(msg))
            # return '%s - <span style="color:red">Error %s. Debe editarse</span>' % (self.nombre, str(msg))
        # if self.cod_cuerpo and self.cod_espec:
        #     return ESPECS[self.cod_cuerpo][self.cod_espec]
        # else:
        #     return self.nombre

    class Meta:
        verbose_name_plural = 'Especialidades en el cupo del profesorado'
        ordering = ['x_dep', 'nombre']

    def __str__(self):
        return '%s %s (%s)' % (self.cupo.nombre, self.nombre, self.cupo.ronda.entidad.name)


class FiltroCupo(models.Model):
    cupo = models.ForeignKey(Cupo, on_delete=models.CASCADE)
    nombre = models.CharField("Nombre del filtro", max_length=150)
    filtro = models.CharField("Texto de filtrado", max_length=50)

    class Meta:
        verbose_name_plural = 'Filtros aplicados al cupo'

    def __str__(self):
        return '%s %s (%s)' % (self.cupo.ronda.entidad.name, self.nombre, self.filtro)


class EtapaEscolarCupo(models.Model):
    cupo = models.ForeignKey(Cupo, on_delete=models.CASCADE)
    nombre = models.CharField('Nombre de la etapa escolar', max_length=250)
    clave_ex = models.CharField("Clave externa", max_length=15, blank=True, null=True)
    orden = models.IntegerField('Orden', default=1)

    class Meta:
        ordering = ['clave_ex', 'nombre']

    def __str__(self):
        return '%s (%s)' % (self.nombre, self.clave_ex)


class CursoCupo(models.Model):
    cupo = models.ForeignKey(Cupo, on_delete=models.CASCADE)
    nombre = models.CharField("Curso", max_length=150)
    etapa_escolar = models.ForeignKey(EtapaEscolarCupo, blank=True, null=True, on_delete=models.CASCADE)
    tipo = models.CharField("Tipo de estudio", max_length=75, null=True, blank=True)
    nombre_especifico = models.CharField("Nombre específico", max_length=150, null=True, blank=True)
    clave_ex = models.CharField("Clave externa", max_length=15, blank=True, null=True)
    num_alumnos = models.IntegerField("Número de alumnos previsto en este curso", default=20)
    orden = models.IntegerField('Orden', default=1)

    @property
    def get_horas_media(self):
        horas = 0
        for materia in self.materia_cupo_set.all():
            horas += materia.horas * materia.num_alumnos
        try:
            return horas / self.num_alumnos
        except:
            return 0

    class Meta:
        ordering = ['etapa_escolar__clave_ex', 'tipo', 'nombre']

    def __str__(self):
        return '%s (%s)' % (self.nombre, self.cupo.ronda.entidad.name)


class Materia_cupo(models.Model):
    cupo = models.ForeignKey(Cupo, on_delete=models.CASCADE)
    especialidad = models.ForeignKey(EspecialidadCupo, blank=True, null=True, on_delete=models.SET_NULL)
    curso = models.ForeignKey(Curso, blank=True, null=True, on_delete=models.CASCADE)
    curso_cupo = models.ForeignKey(CursoCupo, blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField("Nombre de la materia o actividad", max_length=120, null=True, blank=True)
    periodos = models.IntegerField("Número de periodos lectivos por semana", null=True, blank=True)
    horas = models.FloatField("Número de horas lectivas por semana", null=True, blank=True)

cupo/templates/cupoRRHH2pdf.html
{% load mathfilters my_templatetags %}

<style>
    html {
        font-family: Arial, Helvetica, sans-serif;
        font-size: 10pt;
        text-align: justify;
    }

    h1 {
        text-align: center;
    }

    h3 {
        text-align: center;
    }

    table {
        margin-left: auto;
        margin-right: auto;
    }

    .pri {
        line-height: 12px;
        padding: 2px 0px 2px 0px;
        text-align: center;
        font-weight: bold;
        background: #B4B5B0;
    }

    .pri2 {
        text-align: center;
        font-weight: bold;
        background: #B4B5B0;
    }
</style>
{% if not cupo.es_posible_pdf_rrhh %}
    <h1 style="position: absolute;top:300px;color:grey;font-size: 7em;z-index: -1;">Este documento es un borrador</h1>
    <h1 style="position: absolute;bottom:100px;color:coral;z-index: -1;">Para imprimir el documento definitivo
        es necesario bloquear el cupo y publicarlo para RRHH.</h1>
{% endif %}
<span class="gauss_header" style="display: none;">{% autoescape off %}{{ dce.header }}{% endautoescape %}</span>
<span class="gauss_footer" style="display: none;">{% autoescape off %}{{ dce.footer }}{% endautoescape %}</span>
<h1 class="pagebreak" style="padding-bottom: -15px;text-align: center"> Solicitud de profesores interinos de cupo</h1>
<h3>{{ cupo.ronda.entidad.name }} - {{ cupo.ronda.entidad.localidad }} ({{ cupo.ronda.entidad.code }})</h3>
<table style="width:100%;">
    {#    <tr>#}
    {#        <td style="text-align:center;padding-top:2px;" colspan="4"><strong>Especialidad</strong></td>#}
    {#        <td style="text-align:center;padding-top:2px;"><strong>Jornada</strong></td>#}
    {#        <td style="text-align:center;padding-top:2px;font-weight: 700;">Bilingüe</td>#}
    {#        <td style="text-align:center;padding-top:2px;font-weight: 700;">Observaciones</td>#}
    {#    </tr>#}
    {% for p in cupo|interinos %}
    {% ifchanged p.profesorado.especialidad %}
    <tr>
        <td style="border-top: solid 1px darkgray;"
            colspan="5"><b>{{ p.profesorado.especialidad.nombre }}</b>
            &horbar;&horbar; {{ p.profesorado.especialidad.cod_cuerpo }} -
            {{ p.profesorado.especialidad.cod_espec }}</td>
    </tr>
    {% else %}
    <tr>
        <td>&nbsp;</td>
        <td style="border-top: solid 1px coral;font-weight: 800;"
            colspan="4">&nbsp;
        </td>
    </tr>
    {% endifchanged %}
    <tr>
        {#            <td style="text-align:center;padding-top:2px;" colspan="4">{{ p.profesorado.especialidad.nombre }}</td>#}
        <td style="padding-top:2px;padding-left: 25px;width: 24%;">1 {{ p.get_jornada_display }}</td>
        {#            <td style="text-align:center;padding-top:2px;font-weight: 700;width: 30%;">#}
        <td style="text-align:center;padding-top:2px;font-weight: 700;">
            Itinerante {% if p.itinerante %}&#9746;{% else %}&#9744;{% endif %}</td>
        <td style="text-align:center;padding-top:2px;font-weight: 700;">
            No afín {% if p.noafin %}&#9746;{% else %}&#9744;{% endif %}</td>
        <td style="text-align:center;padding-top:2px;font-weight: 700;">
            Bilingüe {% if p.bilingue %} &#9746;{% else %}&#9744;{% endif %}</td>
        <td style="text-align:center;padding-top:2px;font-weight: 700;">
            Sustituto {% if p.sustituto %}&#9746;{% else %}&#9744;{% endif %}</td>
{#        <td style="text-align:center;padding-top:2px;font-weight: 700;">#}
{#            Vacante {% if p.vacante %}&#9746;{% else %}&#9744;{% endif %}</td>#}
    </tr>
    {% if p.observaciones %}
        <tr>
            <td style="padding-top:2px;padding-left: 25px;width: 24%;">&nbsp;</td>
            <td colspan="5"><b>Observaciones:</b> {{ p.observaciones }}</td>
        </tr>
    {% endif %}
    {% if p.observaciones_ocultas %}
        <tr>
            <td style="padding-top:2px;padding-left: 25px;width: 24%;">&nbsp;</td>
            <td colspan="5"><b>Observaciones ocultas:</b> {{ p.observaciones_ocultas }}</td>
        </tr>
    {% endif %}
    {% endfor %}
</table>

cupo/templates/cupo_accordion_content_curso.html
<div id="label_curso{{ c.id }}" class="label secondary">
    <div style="display: inline-block;font-weight: bold;"
         id="texto_nombre_curso{{ c.id }}" data-curso="{{ c.id }}">
        {{ c.nombre }}
    </div>
    <div style="display: inline-block; font-weight: bold;">
        <a data-cupo="{{ c.cupo.id }}" data-curso="{{ c.id }}"
           data-dropdown="drop{{ c.id }}" aria-controls="drop{{ c.id }}" aria-expanded="false">
            <i class="fa fa-gears"></i>
        </a>
    </div>
</div>

<div id="drop{{ c.id }}" data-dropdown-content class="f-dropdown content medium" aria-hidden="true"
     tabindex="-1" aria-autoclose="false">
    <label>Cambia el nombre:
        <input type="text" data-curso="{{ c.id }}" class="change_nombre_curso" value="{{ c.nombre }}">
    </label>
    <label>Cambia la etapa:
        <select class="change_etapa_curso" data-curso="{{ c.id }}">
            {% for etapa in c.cupo.etapaescolarcupo_set.all %}
                <option value="{{ etapa.id }}"
                        {% if c.etapa_escolar == etapa %}selected{% endif %}>{{ etapa.nombre }}</option>
            {% endfor %}
        </select>
    </label>
    <a data-curso="{{ c.id }}" class="select_copy_curso button">
        <i class="fa fa-copy fa-fw"></i> <b>Duplicar</b>
    </a>
    <a data-curso="{{ c.id }}" class="select_del_curso button alert right">
        <i class="fa fa-trash-o fa-fw"></i> <b>Borrar</b>
    </a>
</div>

cupo/templates/cupo_accordion_content_curso_edit.html
<br>
<table>
    <thead>
    <tr>
{#        <th>Orden Curso</th>#}
        <th>Curso</th>
        <th>Etapa</th>
    </tr>
    </thead>
    {% for c in cupo.cursocupo_set.all %}
        <tr>
{#            <td contenteditable="true" class="curso_edit" data-campo="orden"#}
{#                data-curso="{{ c.id }}">{{ c.orden }}</td>#}
            <td contenteditable="true" class="curso_edit" data-campo="nombre"
                data-curso="{{ c.id }}">{{ c.nombre }}</td>
            <td>
                <select class="curso_edit" data-campo="etapa_escolar" data-curso="{{ c.id }}">
                    {% for etapa in cupo.etapaescolarcupo_set.all %}
                        <option value="{{ etapa.id }}"
                                {% if c.etapa_escolar == etapa %}selected{% endif %}>{{ etapa.nombre }}</option>
                    {% endfor %}
                </select></td>
        </tr>
    {% endfor %}
</table>

cupo/templates/cupo_accordion_content_especialidad.html
{% load cupo_extras %}
<div id="label_especialidad{{ e.id }}" class="label secondary" title="{{ e|get_title_cuerpo }}">
    <div style="display: inline-block;font-weight: bold;"
             id="texto_nombre_espec{{ e.id }}" data-espec="{{ e.id }}">{{ e.nombre_oficial }}</div>
        <div style="display: inline-block; font-weight: bold;">
            <a class="select_del_especialidad" data-cupo="{{ e.cupo.id }}" data-especialidad="{{ e.id }}"><i
            class="fa fa-times"></i></a>
        </div>
</div>

cupo/templates/cupo_accordion_content_pubrrhh.html
{% if aprrhh %}
    <a class="checkbox_rrhh" data-cupo="{{ cupo.id }}" style="font-weight: bold;">
        {% if cupo.pub_rrhh %}Sí{% else %}No{% endif %}
    </a>
{% else %}
    <span style="font-weight: bold;color: grey;"
          title="Esta opción no está disponible. Pulsa sobre el icono de información. {{ msg }}">
            {% if cupo.pub_rrhh %}Sí{% else %}No{% endif %}
    </span>
{% endif %}

cupo/templates/estadistica_cupos_accordion_content.html
{% load my_templatetags %}
{% load cupo_extras %}


<div class="row">
    <div class="columns large-8">
        <label>Selecciona el centro educativo:
            <select id="select_entidad{{ curso_escolar.id }}" class="select_entidad">
                <option value="">-------</option>
                {% for entidad in entidades %}
                    <option value="{{ entidad.id }}">{{ entidad.name }} ({{ entidad.localidad }})</option>
                {% endfor %}
            </select>
        </label>
    </div>
</div>
<br>

<div id="div_tablas_estadistica{{ curso_escolar.id }}">
    <table style="width: 100%" id="tabla_estadistica_general{{ curso_escolar.id }}">
        <thead>
        <tr>
            <th colspan="6" class="thtd" style="position: relative;">
                Estadística de cupos
                <span style="position: absolute;right: 10px;">
                    <a class="remove_tabla"><i class="fa fa-times-circle"></i></a>
                </span>
            </th>
        </tr>
        <tr>
            <th class="thtd">Nº de centros</th>
            <th class="thtd">Nº cupos</th>
            <th class="thtd">Borradores</th>
            <th class="thtd">Bloqueados</th>
            <th class="thtd">Publicados RRHH</th>
            <th class="thtd">Fechas realización</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="thtd">{{ estad.n_centros }}</td>
            <td class="thtd">{{ estad.n_cupos }}</td>
            <td class="thtd">{{ estad.n_borradores }}</td>
            <td class="thtd">{{ estad.n_bloqueados }}</td>
            <td class="thtd">{{ estad.n_pubrrhh }}</td>
            <td class="thtd">{{ estad.min_fecha }} - {{ estad.max_fecha }}</td>
        </tr>
        </tbody>
    </table>
    <div id="div_estadistica_cupos{{ curso_escolar.id }}">

    </div>
</div>

cupo/templates/estadistica_cupos_html2pdf.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Informe con estadística de cupos</title>

    <style>
        html {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 10pt;
            text-align: justify;
        }

        h1 {
            text-align: center;
         }
        th, td {
            text-align: center;
            border: 1px gray solid!important;
        }

        table {
            margin-left: auto;
            margin-right: auto;
            margin-bottom: 30px;
            border-collapse: collapse!important;
        }
    </style>
</head>
<body>
<span class="gauss_header" style="display: none;">{% autoescape off %}{{ dce.header }}{% endautoescape %}</span>
<span class="gauss_footer" style="display: none;">{% autoescape off %}{{ dce.footer }}{% endautoescape %}</span>
<h1>INFORME ESTADÍSTICA CUPOS</h1>
{% autoescape off %}
{{ tablas }}
{% endautoescape %}
</body>
</html>

cupo/templates/plantilla_organica_accordion_cons.html
{% load entidades_extras %}
{% load cupo_extras %}
{% for conservatorio in conservatorios %}
    <input type="hidden" name="conservatorios" value="{{ conservatorio.id }}">

    <dd class="accordion-navigation" id="accordion{{ conservatorio.id }}"
        style="border-bottom: dotted 1px black">
        <a href="#panel{{ conservatorio.id }}">
            <i id="circle{{ conservatorio.id }}" class="fa fa-plus-circle circle_icon"></i>
            <b id="asunto{{ conservatorio.id }}">Plantilla Orgánica: {{ conservatorio.ronda }}</b> -- <span
                style="color: green; padding-right: 20px;"><i
                class="fa fa-user"></i> {{ conservatorio.g_e.gauser.get_full_name }}</span>
            ({{ conservatorio.creado|date:"d-m-Y H:i" }})

            {% if buscadas %}
                <span style="color: red; padding-left: 100px;"><i class="fa fa-check"></i> </span>
            {% endif %}
        </a>

        <div id="panel{{ conservatorio.id }}" class="content accordion-conservatorio" data-id="{{ conservatorio.id }}">
            <table style="width: 100%;position: relative;">
                <thead id="cabecera_tabla_vacantes">
                <tr>
                    <th colspan="7" style="color: #1b75bb;text-align: center;width: {{ po.anchura_cols.0 }}%;">Plazas de
                        plantilla
                        orgánica actualizadas a {{ conservatorio|get_fecha_plazas }}</th>
                </tr>
                <tr>
                    <th>Especialidad</th>
                    <th>Cuerpo</th>
                    <th>Código</th>
                    <th>Tipo</th>
                    <th>Plazas</th>
                    <th>Ocupadas</th>
                    <th>Vacantes</th>
                </tr>
                </thead>
                <tbody>
                {% for plaza in conservatorio|get_plazas %}
                    <tr>
                        <td>{{ plaza.nombre }}</td>
                        <td>{{ plaza.cod_cuerpo }}</td>
                        <td>{{ plaza.cod_especialidad }}</td>
                        <td {% if plaza.tipo == 'ord' %}title="Plaza ordinaria"
                            {% elif plaza.tipo == 'com' %}title="Plaza compartida con otros centros de la misma localidad"
                            {% elif plaza.tipo == 'iti' %}title="Plaza con carácter itinerante entre diferentes localidades"
                            {% else %}title="Plaza bilingüe"{% endif %}>{{ plaza.get_tipo_display }}</td>
                        <td>{{ plaza.plazas }}</td>
                        <td>{{ plaza.ocupadas }}</td>
                        <td>{{ plaza.vacantes }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>


{#            <table style="width: 100%;position: relative;">#}
{#                <thead id="cabecera_tabla_po_entidad{{ conservatorio.id }}">#}
{#                <tr>#}
{#                    <th style="color: #1b75bb;text-align: center;width: {{ po.anchura_cols.0 }}%;">Especialidades y#}
{#                        Docentes#}
{#                    </th>#}
{#                    {% for apartado in po|get_apartados %}#}
{#                        <th style="color: #1b75bb;text-align: center;width: {{ apartado.width }}%"#}
{#                            colspan="{{ apartado.colspan }}">#}
{#                            {{ apartado.nombre }}#}
{#                        </th>#}
{#                    {% endfor %}#}
{#                    <th style="color: #1b75bb;text-align: center;width: {{ po.anchura_cols.2 }}%;" colspan="3">Horas#}
{#                        calculadas#}
{#                    </th>#}
{#                </tr>#}
{#                </thead>#}
{#                <tbody id="tbody_docente{{ po.id }}">#}
{#                {% include "plantilla_organica_accordion_content_tbody.html" %}#}
{#                </tbody>#}
{#            </table>#}
            <table>
                {% for puesto in conservatorio|puestos_especialidad %}
                    <tr>
                    <td>{{ puesto }}</td>
{#                        <td>{{ conservatorio|get_vacantes:puesto }}</td>#}
                        <td>{{ profe.puesto }}</td>
                        <td>{{ profe.jornada_contratada }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </dd>
{% endfor %}